// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.ScratchMsgs.allLocales');

goog.require('Blockly.ScratchMsgs');

Blockly.ScratchMsgs.locales["es"] =
{
  "CONTROL_FOREVER": "por siempre",
  "CONTROL_REPEAT": "repetir %1",
  "CONTROL_IF": "si %1 entonces",
  "CONTROL_ELSE": "si no",
  "CONTROL_STOP": "detener",
  "CONTROL_STOP_ALL": "todos",
  "CONTROL_STOP_THIS": "este programa",
  "CONTROL_STOP_OTHER": "otros programas en el objeto",
  "CONTROL_WAIT": "esperar %1 segundos",
  "CONTROL_WAITUNTIL": "esperar hasta que %1",
  "CONTROL_REPEATUNTIL": "repetir hasta que %1",
  "CONTROL_WHILE": "mientras %1",
  "CONTROL_FOREACH": "para cada %1 de %2",
  "CONTROL_STARTASCLONE": "al comenzar como clon",
  "CONTROL_CREATECLONEOF": "crear clon de %1",
  "CONTROL_CREATECLONEOF_MYSELF": "mí mismo",
  "CONTROL_DELETETHISCLONE": "eliminar este clon",
  "CONTROL_COUNTER": "contador",
  "CONTROL_INCRCOUNTER": "incrementar contador",
  "CONTROL_CLEARCOUNTER": "borrar contador",
  "CONTROL_ALLATONCE": "todo de una vez",
  "DATA_SETVARIABLETO": "dar a %1 el valor %2",
  "DATA_CHANGEVARIABLEBY": "sumar a %1 %2",
  "DATA_SHOWVARIABLE": "mostrar variable %1",
  "DATA_HIDEVARIABLE": "esconder variable %1",
  "DATA_ADDTOLIST": "añadir %1 a %2",
  "DATA_DELETEOFLIST": "eliminar %1 de %2",
  "DATA_DELETEALLOFLIST": "eliminar todos de %1",
  "DATA_INSERTATLIST": "insertar %1 en %2 de %3",
  "DATA_REPLACEITEMOFLIST": "reemplazar elemento %1 de %2 con %3",
  "DATA_ITEMOFLIST": "elemento %1 de %2",
  "DATA_ITEMNUMOFLIST": "# de elemento de %1 en %2",
  "DATA_LENGTHOFLIST": "longitud de %1",
  "DATA_LISTCONTAINSITEM": "¿%2 está en %1?",
  "DATA_SHOWLIST": "mostrar lista %1",
  "DATA_HIDELIST": "esconder lista %1",
  "DATA_INDEX_ALL": "todos",
  "DATA_INDEX_LAST": "último",
  "DATA_INDEX_RANDOM": "aleatorio",
  "EVENT_WHENFLAGCLICKED": "al hacer clic en %1",
  "EVENT_WHENTHISSPRITECLICKED": "al hacer clic en este objeto",
  "EVENT_WHENSTAGECLICKED": "al hacer clic en el escenario",
  "EVENT_WHENTOUCHINGOBJECT": "cuando el objeto toque %1",
  "EVENT_WHENBROADCASTRECEIVED": "al recibir %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "cuando el fondo cambie a %1",
  "EVENT_WHENGREATERTHAN": "cuando %1 > %2",
  "EVENT_WHENGREATERTHAN_TIMER": "cronómetro",
  "EVENT_WHENGREATERTHAN_LOUDNESS": "volumen del sonido",
  "EVENT_BROADCAST": "enviar %1",
  "EVENT_BROADCASTANDWAIT": "enviar %1 y esperar",
  "EVENT_WHENKEYPRESSED": "al presionar tecla %1",
  "EVENT_WHENKEYPRESSED_SPACE": "espacio",
  "EVENT_WHENKEYPRESSED_LEFT": "flecha izquierda",
  "EVENT_WHENKEYPRESSED_RIGHT": "flecha derecha",
  "EVENT_WHENKEYPRESSED_DOWN": "flecha abajo",
  "EVENT_WHENKEYPRESSED_UP": "flecha arriba",
  "EVENT_WHENKEYPRESSED_ANY": "cualquiera",
  "LOOKS_SAYFORSECS": "decir %1 durante %2 segundos",
  "LOOKS_SAY": "decir %1",
  "LOOKS_HELLO": "¡Hola!",
  "LOOKS_THINKFORSECS": "pensar %1 durante %2 segundos",
  "LOOKS_THINK": "pensar %1",
  "LOOKS_HMM": "Umm...",
  "LOOKS_SHOW": "mostrar",
  "LOOKS_HIDE": "esconder",
  "LOOKS_HIDEALLSPRITES": "esconder todos los objetos",
  "LOOKS_EFFECT_COLOR": "color",
  "LOOKS_EFFECT_FISHEYE": "ojo de pez",
  "LOOKS_EFFECT_WHIRL": "remolino",
  "LOOKS_EFFECT_PIXELATE": "pixelar",
  "LOOKS_EFFECT_MOSAIC": "mosaico",
  "LOOKS_EFFECT_BRIGHTNESS": "brillo",
  "LOOKS_EFFECT_GHOST": "desvanecer",
  "LOOKS_CHANGEEFFECTBY": "sumar al efecto %1 %2",
  "LOOKS_SETEFFECTTO": "dar al efecto %1 el valor %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "quitar efectos gráficos",
  "LOOKS_CHANGESIZEBY": "cambiar tamaño por %1",
  "LOOKS_SETSIZETO": "fijar tamaño al %1 %",
  "LOOKS_SIZE": "tamaño",
  "LOOKS_CHANGESTRETCHBY": "sumar al estiramiento %1",
  "LOOKS_SETSTRETCHTO": "fijar estiramiento al %1 %",
  "LOOKS_SWITCHCOSTUMETO": "cambiar disfraz a %1",
  "LOOKS_NEXTCOSTUME": "siguiente disfraz",
  "LOOKS_SWITCHBACKDROPTO": "cambiar fondo a %1",
  "LOOKS_GOTOFRONTBACK": "ir a capa %1",
  "LOOKS_GOTOFRONTBACK_FRONT": "delantera",
  "LOOKS_GOTOFRONTBACK_BACK": "trasera",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "ir %2 capas hacia %1",
  "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "delante",
  "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "atrás",
  "LOOKS_BACKDROPNUMBERNAME": "%1 de fondo",
  "LOOKS_COSTUMENUMBERNAME": "%1 de disfraz",
  "LOOKS_NUMBERNAME_NUMBER": "número",
  "LOOKS_NUMBERNAME_NAME": "nombre",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "cambiar fondo a %1 y esperar",
  "LOOKS_NEXTBACKDROP_BLOCK": "siguiente fondo",
  "LOOKS_NEXTBACKDROP": "siguiente fondo",
  "LOOKS_PREVIOUSBACKDROP": "fondo anterior",
  "LOOKS_RANDOMBACKDROP": "fondo aleatorio",
  "MOTION_MOVESTEPS": "mover %1 pasos",
  "MOTION_TURNLEFT": "girar %1 %2 grados",
  "MOTION_TURNRIGHT": "girar %1 %2 grados",
  "MOTION_POINTINDIRECTION": "apuntar en dirección %1",
  "MOTION_POINTTOWARDS": "apuntar hacia %1",
  "MOTION_POINTTOWARDS_POINTER": "puntero del ratón",
  "MOTION_POINTTOWARDS_RANDOM": "dirección aleatoria",
  "MOTION_GOTO": "ir a %1",
  "MOTION_GOTO_POINTER": "puntero del ratón",
  "MOTION_GOTO_RANDOM": "posición aleatoria",
  "MOTION_GOTOXY": "ir a x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "deslizar en %1 segs a x: %2 y: %3",
  "MOTION_GLIDETO": "deslizar en %1 segs a %2",
  "MOTION_GLIDETO_POINTER": "puntero del ratón",
  "MOTION_GLIDETO_RANDOM": "posición aleatoria",
  "MOTION_CHANGEXBY": "sumar a x %1",
  "MOTION_SETX": "dar a x el valor %1",
  "MOTION_CHANGEYBY": "sumar a y %1",
  "MOTION_SETY": "dar a y el valor %1",
  "MOTION_IFONEDGEBOUNCE": "si toca un borde, rebotar",
  "MOTION_SETROTATIONSTYLE": "fijar estilo de rotación a %1",
  "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "izquierda-derecha",
  "MOTION_SETROTATIONSTYLE_DONTROTATE": "no rotar",
  "MOTION_SETROTATIONSTYLE_ALLAROUND": "en todas direcciones",
  "MOTION_XPOSITION": "posición en x",
  "MOTION_YPOSITION": "posición en y",
  "MOTION_DIRECTION": "dirección",
  "MOTION_SCROLLRIGHT": "desplazar a la derecha %1",
  "MOTION_SCROLLUP": "desplazar arriba %1",
  "MOTION_ALIGNSCENE": "alinear escena %1",
  "MOTION_ALIGNSCENE_BOTTOMLEFT": "abajo a la izquierda",
  "MOTION_ALIGNSCENE_BOTTOMRIGHT": "abajo a la derecha",
  "MOTION_ALIGNSCENE_MIDDLE": "al centro",
  "MOTION_ALIGNSCENE_TOPLEFT": "arriba a la izquierda",
  "MOTION_ALIGNSCENE_TOPRIGHT": "arriba a la derecha",
  "MOTION_XSCROLL": "desplazamiento en x",
  "MOTION_YSCROLL": "desplazamiento en y",
  "MOTION_STAGE_SELECTED": "Escenario seleccionado: no hay bloques de movimiento",
  "MOTION_MOVEGRIDS": "mover %1 cuadrículas (40 pasos)",
  "OPERATORS_ADD": "%1 + %2",
  "OPERATORS_SUBTRACT": "%1 - %2",
  "OPERATORS_MULTIPLY": "%1 * %2",
  "OPERATORS_DIVIDE": "%1 / %2",
  "OPERATORS_RANDOM": "número aleatorio entre %1 y %2",
  "OPERATORS_GT": "%1 > %2",
  "OPERATORS_LT": "%1 < %2",
  "OPERATORS_EQUALS": "%1 = %2",
  "OPERATORS_AND": "%1 y %2",
  "OPERATORS_OR": "%1 o %2",
  "OPERATORS_NOT": "no %1",
  "OPERATORS_JOIN": "unir %1 %2",
  "OPERATORS_JOIN_APPLE": "manzana",
  "OPERATORS_JOIN_BANANA": "plátano",
  "OPERATORS_LETTEROF": "letra %1 de %2",
  "OPERATORS_LETTEROF_APPLE": "a",
  "OPERATORS_LENGTH": "longitud de %1",
  "OPERATORS_CONTAINS": "¿%2 está en %1?",
  "OPERATORS_MOD": "%1 módulo %2",
  "OPERATORS_ROUND": "redondear %1",
  "OPERATORS_MATHOP": "%1 de %2",
  "OPERATORS_MATHOP_ABS": "valor absoluto",
  "OPERATORS_MATHOP_FLOOR": "suelo",
  "OPERATORS_MATHOP_CEILING": "techo",
  "OPERATORS_MATHOP_SQRT": "raíz cuadrada",
  "OPERATORS_MATHOP_SIN": "sen",
  "OPERATORS_MATHOP_COS": "cos",
  "OPERATORS_MATHOP_TAN": "tan",
  "OPERATORS_MATHOP_ASIN": "arcsen",
  "OPERATORS_MATHOP_ACOS": "arccos",
  "OPERATORS_MATHOP_ATAN": "arctan",
  "OPERATORS_MATHOP_LN": "ln",
  "OPERATORS_MATHOP_LOG": "log",
  "OPERATORS_MATHOP_EEXP": "e ^",
  "OPERATORS_MATHOP_10EXP": "10 ^",
  "PROCEDURES_DEFINITION": "definir %1",
  "SENSING_TOUCHINGOBJECT": "¿tocando %1?",
  "SENSING_TOUCHINGOBJECT_POINTER": "puntero del ratón",
  "SENSING_TOUCHINGOBJECT_EDGE": "borde",
  "SENSING_TOUCHINGCOLOR": "¿tocando el color %1?",
  "SENSING_COLORISTOUCHINGCOLOR": "¿color %1 tocando %2?",
  "SENSING_DISTANCETO": "distancia a %1",
  "SENSING_DISTANCETO_POINTER": "puntero del ratón",
  "SENSING_ASKANDWAIT": "preguntar %1 y esperar",
  "SENSING_ASK_TEXT": "¿Cómo te llamas?",
  "SENSING_ANSWER": "respuesta",
  "SENSING_KEYPRESSED": "¿tecla %1 presionada?",
  "SENSING_MOUSEDOWN": "¿ratón presionado?",
  "SENSING_MOUSEX": "posición x del ratón",
  "SENSING_MOUSEY": "posición y del ratón",
  "SENSING_SETDRAGMODE": "fijar modo de arrastre a %1",
  "SENSING_SETDRAGMODE_DRAGGABLE": "arrastrable",
  "SENSING_SETDRAGMODE_NOTDRAGGABLE": "no arrastrable",
  "SENSING_LOUDNESS": "volumen del sonido",
  "SENSING_LOUD": "¿ruidoso?",
  "SENSING_TIMER": "cronómetro",
  "SENSING_RESETTIMER": "reiniciar cronómetro",
  "SENSING_OF": "%1 de %2",
  "SENSING_OF_XPOSITION": "posición en x",
  "SENSING_OF_YPOSITION": "posición en y",
  "SENSING_OF_DIRECTION": "dirección",
  "SENSING_OF_COSTUMENUMBER": "# de disfraz",
  "SENSING_OF_COSTUMENAME": "nombre de disfraz",
  "SENSING_OF_SIZE": "tamaño",
  "SENSING_OF_VOLUME": "volumen",
  "SENSING_OF_BACKDROPNUMBER": "# de fondo",
  "SENSING_OF_BACKDROPNAME": "nombre de fondo",
  "SENSING_OF_STAGE": "Escenario",
  "SENSING_CURRENT": "%1 actual",
  "SENSING_CURRENT_YEAR": "año",
  "SENSING_CURRENT_MONTH": "mes",
  "SENSING_CURRENT_DATE": "día",
  "SENSING_CURRENT_DAYOFWEEK": "día de la semana",
  "SENSING_CURRENT_HOUR": "hora",
  "SENSING_CURRENT_MINUTE": "minuto",
  "SENSING_CURRENT_SECOND": "segundo",
  "SENSING_DAYSSINCE2000": "días desde el 2000",
  "SENSING_USERNAME": "nombre de usuario",
  "SENSING_USERID": "id de usuario",
  "SOUND_PLAY": "iniciar sonido %1",
  "SOUND_PLAYUNTILDONE": "tocar sonido %1 hasta que termine",
  "SOUND_STOPALLSOUNDS": "detener todos los sonidos",
  "SOUND_SETEFFECTO": "dar al efecto %1 el valor %2",
  "SOUND_CHANGEEFFECTBY": "sumar al efecto %1 %2",
  "SOUND_CLEAREFFECTS": "quitar efectos de sonido",
  "SOUND_EFFECTS_PITCH": "altura",
  "SOUND_EFFECTS_PAN": "balance izquierda/derecha",
  "SOUND_CHANGEVOLUMEBY": "cambiar volumen por %1",
  "SOUND_SETVOLUMETO": "fijar volumen al %1%",
  "SOUND_VOLUME": "volumen",
  "SOUND_RECORD": "grabar...",
  "CATEGORY_MOTION": "Movimiento",
  "CATEGORY_LOOKS": "Apariencia",
  "CATEGORY_SOUND": "Sonido",
  "CATEGORY_EVENTS": "Eventos",
  "CATEGORY_CONTROL": "Control",
  "CATEGORY_SENSING": "Sensores",
  "CATEGORY_OPERATORS": "Operadores",
  "CATEGORY_VARIABLES": "Variables",
  "CATEGORY_MYBLOCKS": "Mis bloques",
  "DUPLICATE": "Duplicar",
  "DELETE": "Eliminar",
  "ADD_COMMENT": "Añadir comentario",
  "REMOVE_COMMENT": "Eliminar comentario",
  "DELETE_BLOCK": "Eliminar bloque",
  "DELETE_X_BLOCKS": "Eliminar %1 bloques",
  "DELETE_ALL_BLOCKS": "¿Eliminar los %1 bloques?",
  "CLEAN_UP": "Ordenar bloques",
  "HELP": "Ayuda",
  "UNDO": "Deshacer",
  "REDO": "Rehacer",
  "FRAME": "Marco",
  "COLLAPSED_X_BLOCKS": "Colapsado %1 bloques",
  "COLOR": "Color",
  "CREATE_FRAME": "Crear Marco",
  "EDIT_PROCEDURE": "Editar",
  "SHOW_PROCEDURE_DEFINITION": "Ir a definición",
  "WORKSPACE_COMMENT_DEFAULT_TEXT": "Di algo...",
  "COLOUR_HUE_LABEL": "Color",
  "COLOUR_SATURATION_LABEL": "Saturación",
  "COLOUR_BRIGHTNESS_LABEL": "Brillo",
  "CHANGE_VALUE_TITLE": "Cambiar valor:",
  "RENAME_VARIABLE": "Renombrar variable",
  "RENAME_VARIABLE_TITLE": "Renombrar todas las variables \"%1\" a:",
  "RENAME_VARIABLE_MODAL_TITLE": "Renombrar variable",
  "NEW_VARIABLE": "Crear una variable",
  "NEW_VARIABLE_TITLE": "Nombre de la variable:",
  "VARIABLE_MODAL_TITLE": "Nueva variable",
  "VARIABLE_ALREADY_EXISTS": "Ya existe una variable llamada \"%1\".",
  "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "Ya existe una variable llamada \"%1\" para otra variable de tipo \"%2\".",
  "DELETE_VARIABLE_CONFIRMATION": "¿Eliminar %1 usos de la variable \"%2\"?",
  "CANNOT_DELETE_VARIABLE_PROCEDURE": "No se puede eliminar la variable \"%1\" porque es parte de la definición de la función \"%2\"",
  "DELETE_VARIABLE": "Eliminar la variable \"%1\"",
  "DISABLED_VARIABLE": 'Este "%1" solo se puede eliminar o renombrar en el escenario.',
  "VARIABLE": "variable",
  "LIST": "lista",
  "NEW_PROCEDURE": "Crear un bloque",
  "PROCEDURE_ALREADY_EXISTS": "Ya existe un procedimiento llamado \"%1\".",
  "PROCEDURE_DEFAULT_NAME": "nombre del bloque",
  "PROCEDURE_USED": "Antes de eliminar la definición del bloque debes eliminar todos sus usos",
  "Global_PROCEDURE_USED": "Para eliminar una definición de bloque, primero quite todos los usos del bloque del sprite [%1]",
  "NEW_LIST": "Crear una lista",
  "NEW_LIST_TITLE": "Nombre de la lista:",
  "LIST_MODAL_TITLE": "Nueva lista",
  "LIST_ALREADY_EXISTS": "Ya existe una lista llamada \"%1\".",
  "RENAME_LIST_TITLE": "Renombrar todas las listas \"%1\" a:",
  "RENAME_LIST_MODAL_TITLE": "Renombrar lista",
  "DEFAULT_LIST_ITEM": "cosa",
  "DELETE_LIST": "Eliminar la lista \"%1\"",
  "RENAME_LIST": "Renombrar lista",
  "NEW_BROADCAST_MESSAGE": "Nuevo mensaje",
  "NEW_BROADCAST_MESSAGE_TITLE": "Nombre del mensaje:",
  "BROADCAST_MODAL_TITLE": "Nuevo Mensaje",
  "DEFAULT_BROADCAST_MESSAGE_NAME": "mensaje1",
  "PROCEDURE_RETURN": "devolver %1",
};

Blockly.ScratchMsgs.locales["en"] =
{
  "CONTROL_FOREVER": "forever",
  "CONTROL_REPEAT": "repeat %1",
  "CONTROL_IF": "if %1 then",
  "CONTROL_ELSE": "else",
  "CONTROL_STOP": "stop",
  "CONTROL_STOP_ALL": "all",
  "CONTROL_STOP_THIS": "this script",
  "CONTROL_STOP_OTHER": "other scripts in sprite",
  "CONTROL_WAIT": "wait %1 seconds",
  "CONTROL_WAITUNTIL": "wait until %1",
  "CONTROL_REPEATUNTIL": "repeat until %1",
  "CONTROL_WHILE": "while %1",
  "CONTROL_FOREACH": "for each %1 in %2",
  "CONTROL_STARTASCLONE": "when I start as a clone",
  "CONTROL_CREATECLONEOF": "create clone of %1",
  "CONTROL_CREATECLONEOF_MYSELF": "myself",
  "CONTROL_DELETETHISCLONE": "delete this clone",
  "CONTROL_COUNTER": "counter",
  "CONTROL_INCRCOUNTER": "increment counter",
  "CONTROL_CLEARCOUNTER": "clear counter",
  "CONTROL_ALLATONCE": "all at once",
  "DATA_SETVARIABLETO": "set %1 to %2",
  "DATA_CHANGEVARIABLEBY": "change %1 by %2",
  "DATA_SHOWVARIABLE": "show variable %1",
  "DATA_HIDEVARIABLE": "hide variable %1",
  "DATA_ADDTOLIST": "add %1 to %2",
  "DATA_DELETEOFLIST": "delete %1 of %2",
  "DATA_DELETEALLOFLIST": "delete all of %1",
  "DATA_INSERTATLIST": "insert %1 at %2 of %3",
  "DATA_REPLACEITEMOFLIST": "replace item %1 of %2 with %3",
  "DATA_ITEMOFLIST": "item %1 of %2",
  "DATA_ITEMNUMOFLIST": "item # of %1 in %2",
  "DATA_LENGTHOFLIST": "length of %1",
  "DATA_LISTCONTAINSITEM": "%1 contains %2?",
  "DATA_SHOWLIST": "show list %1",
  "DATA_HIDELIST": "hide list %1",
  "DATA_INDEX_ALL": "all",
  "DATA_INDEX_LAST": "last",
  "DATA_INDEX_RANDOM": "random",
  "EVENT_WHENFLAGCLICKED": "when %1 clicked",
  "EVENT_WHENTHISSPRITECLICKED": "when this sprite clicked",
  "EVENT_WHENSTAGECLICKED": "when stage clicked",
  "EVENT_WHENTOUCHINGOBJECT": "when this sprite touches %1",
  "EVENT_WHENBROADCASTRECEIVED": "when I receive %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "when backdrop switches to %1",
  "EVENT_WHENGREATERTHAN": "when %1 > %2",
  "EVENT_WHENGREATERTHAN_TIMER": "timer",
  "EVENT_WHENGREATERTHAN_LOUDNESS": "loudness",
  "EVENT_BROADCAST": "broadcast %1",
  "EVENT_BROADCASTANDWAIT": "broadcast %1 and wait",
  "EVENT_WHENKEYPRESSED": "when %1 key pressed",
  "EVENT_WHENKEYPRESSED_SPACE": "space",
  "EVENT_WHENKEYPRESSED_LEFT": "left arrow",
  "EVENT_WHENKEYPRESSED_RIGHT": "right arrow",
  "EVENT_WHENKEYPRESSED_DOWN": "down arrow",
  "EVENT_WHENKEYPRESSED_UP": "up arrow",
  "EVENT_WHENKEYPRESSED_ANY": "any",
  "LOOKS_SAYFORSECS": "say %1 for %2 seconds",
  "LOOKS_SAY": "say %1",
  "LOOKS_HELLO": "Hello!",
  "LOOKS_THINKFORSECS": "think %1 for %2 seconds",
  "LOOKS_THINK": "think %1",
  "LOOKS_HMM": "Hmm...",
  "LOOKS_SHOW": "show",
  "LOOKS_HIDE": "hide",
  "LOOKS_HIDEALLSPRITES": "hide all sprites",
  "LOOKS_EFFECT_COLOR": "color",
  "LOOKS_EFFECT_FISHEYE": "fisheye",
  "LOOKS_EFFECT_WHIRL": "whirl",
  "LOOKS_EFFECT_PIXELATE": "pixelate",
  "LOOKS_EFFECT_MOSAIC": "mosaic",
  "LOOKS_EFFECT_BRIGHTNESS": "brightness",
  "LOOKS_EFFECT_GHOST": "ghost",
  "LOOKS_CHANGEEFFECTBY": "change %1 effect by %2",
  "LOOKS_SETEFFECTTO": "set %1 effect to %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "clear graphic effects",
  "LOOKS_CHANGESIZEBY": "change size by %1",
  "LOOKS_SETSIZETO": "set size to %1 %",
  "LOOKS_SIZE": "size",
  "LOOKS_CHANGESTRETCHBY": "change stretch by %1",
  "LOOKS_SETSTRETCHTO": "set stretch to %1 %",
  "LOOKS_SWITCHCOSTUMETO": "switch costume to %1",
  "LOOKS_NEXTCOSTUME": "next costume",
  "LOOKS_SWITCHBACKDROPTO": "switch backdrop to %1",
  "LOOKS_GOTOFRONTBACK": "go to %1 layer",
  "LOOKS_GOTOFRONTBACK_FRONT": "front",
  "LOOKS_GOTOFRONTBACK_BACK": "back",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "go %1 %2 layers",
  "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "forward",
  "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "backward",
  "LOOKS_BACKDROPNUMBERNAME": "backdrop %1",
  "LOOKS_COSTUMENUMBERNAME": "costume %1",
  "LOOKS_NUMBERNAME_NUMBER": "number",
  "LOOKS_NUMBERNAME_NAME": "name",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "switch backdrop to %1 and wait",
  "LOOKS_NEXTBACKDROP_BLOCK": "next backdrop",
  "LOOKS_NEXTBACKDROP": "next backdrop",
  "LOOKS_PREVIOUSBACKDROP": "previous backdrop",
  "LOOKS_RANDOMBACKDROP": "random backdrop",
  "MOTION_MOVESTEPS": "move %1 steps",
  "MOTION_TURNLEFT": "turn %1 %2 degrees",
  "MOTION_TURNRIGHT": "turn %1 %2 degrees",
  "MOTION_POINTINDIRECTION": "point in direction %1",
  "MOTION_POINTTOWARDS": "point towards %1",
  "MOTION_POINTTOWARDS_POINTER": "mouse-pointer",
  "MOTION_POINTTOWARDS_RANDOM": "random direction",
  "MOTION_GOTO": "go to %1",
  "MOTION_GOTO_POINTER": "mouse-pointer",
  "MOTION_GOTO_RANDOM": "random position",
  "MOTION_GOTOXY": "go to x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "glide %1 secs to x: %2 y: %3",
  "MOTION_GLIDETO": "glide %1 secs to %2",
  "MOTION_GLIDETO_POINTER": "mouse-pointer",
  "MOTION_GLIDETO_RANDOM": "random position",
  "MOTION_CHANGEXBY": "change x by %1",
  "MOTION_SETX": "set x to %1",
  "MOTION_CHANGEYBY": "change y by %1",
  "MOTION_SETY": "set y to %1",
  "MOTION_IFONEDGEBOUNCE": "if on edge, bounce",
  "MOTION_SETROTATIONSTYLE": "set rotation style %1",
  "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "left-right",
  "MOTION_SETROTATIONSTYLE_DONTROTATE": "don't rotate",
  "MOTION_SETROTATIONSTYLE_ALLAROUND": "all around",
  "MOTION_XPOSITION": "x position",
  "MOTION_YPOSITION": "y position",
  "MOTION_DIRECTION": "direction",
  "MOTION_SCROLLRIGHT": "scroll right %1",
  "MOTION_SCROLLUP": "scroll up %1",
  "MOTION_ALIGNSCENE": "align scene %1",
  "MOTION_ALIGNSCENE_BOTTOMLEFT": "bottom-left",
  "MOTION_ALIGNSCENE_BOTTOMRIGHT": "bottom-right",
  "MOTION_ALIGNSCENE_MIDDLE": "middle",
  "MOTION_ALIGNSCENE_TOPLEFT": "top-left",
  "MOTION_ALIGNSCENE_TOPRIGHT": "top-right",
  "MOTION_XSCROLL": "x scroll",
  "MOTION_YSCROLL": "y scroll",
  "MOTION_STAGE_SELECTED": "Stage selected: no motion blocks",
  "MOTION_MOVEGRIDS": "move %1 grids(40 steps)",
  "OPERATORS_ADD": "%1 + %2",
  "OPERATORS_SUBTRACT": "%1 - %2",
  "OPERATORS_MULTIPLY": "%1 * %2",
  "OPERATORS_DIVIDE": "%1 / %2",
  "OPERATORS_RANDOM": "pick random %1 to %2",
  "OPERATORS_GT": "%1 > %2",
  "OPERATORS_LT": "%1 < %2",
  "OPERATORS_EQUALS": "%1 = %2",
  "OPERATORS_AND": "%1 and %2",
  "OPERATORS_OR": "%1 or %2",
  "OPERATORS_NOT": "not %1",
  "OPERATORS_JOIN": "join %1 %2",
  "OPERATORS_JOIN_APPLE": "apple",
  "OPERATORS_JOIN_BANANA": "banana",
  "OPERATORS_LETTEROF": "letter %1 of %2",
  "OPERATORS_LETTEROF_APPLE": "a",
  "OPERATORS_LENGTH": "length of %1",
  "OPERATORS_CONTAINS": "%1 contains %2?",
  "OPERATORS_MOD": "%1 mod %2",
  "OPERATORS_ROUND": "round %1",
  "OPERATORS_MATHOP": "%1 of %2",
  "OPERATORS_MATHOP_ABS": "abs",
  "OPERATORS_MATHOP_FLOOR": "floor",
  "OPERATORS_MATHOP_CEILING": "ceiling",
  "OPERATORS_MATHOP_SQRT": "sqrt",
  "OPERATORS_MATHOP_SIN": "sin",
  "OPERATORS_MATHOP_COS": "cos",
  "OPERATORS_MATHOP_TAN": "tan",
  "OPERATORS_MATHOP_ASIN": "asin",
  "OPERATORS_MATHOP_ACOS": "acos",
  "OPERATORS_MATHOP_ATAN": "atan",
  "OPERATORS_MATHOP_LN": "ln",
  "OPERATORS_MATHOP_LOG": "log",
  "OPERATORS_MATHOP_EEXP": "e ^",
  "OPERATORS_MATHOP_10EXP": "10 ^",
  "PROCEDURES_DEFINITION": "define %1",
  "SENSING_TOUCHINGOBJECT": "touching %1?",
  "SENSING_TOUCHINGOBJECT_POINTER": "mouse-pointer",
  "SENSING_TOUCHINGOBJECT_EDGE": "edge",
  "SENSING_TOUCHINGCOLOR": "touching color %1?",
  "SENSING_COLORISTOUCHINGCOLOR": "color %1 is touching %2?",
  "SENSING_DISTANCETO": "distance to %1",
  "SENSING_DISTANCETO_POINTER": "mouse-pointer",
  "SENSING_ASKANDWAIT": "ask %1 and wait",
  "SENSING_ASK_TEXT": "What's your name?",
  "SENSING_ANSWER": "answer",
  "SENSING_KEYPRESSED": "key %1 pressed?",
  "SENSING_MOUSEDOWN": "mouse down?",
  "SENSING_MOUSEX": "mouse x",
  "SENSING_MOUSEY": "mouse y",
  "SENSING_SETDRAGMODE": "set drag mode %1",
  "SENSING_SETDRAGMODE_DRAGGABLE": "draggable",
  "SENSING_SETDRAGMODE_NOTDRAGGABLE": "not draggable",
  "SENSING_LOUDNESS": "loudness",
  "SENSING_LOUD": "loud?",
  "SENSING_TIMER": "timer",
  "SENSING_RESETTIMER": "reset timer",
  "SENSING_OF": "%1 of %2",
  "SENSING_OF_XPOSITION": "x position",
  "SENSING_OF_YPOSITION": "y position",
  "SENSING_OF_DIRECTION": "direction",
  "SENSING_OF_COSTUMENUMBER": "costume #",
  "SENSING_OF_COSTUMENAME": "costume name",
  "SENSING_OF_SIZE": "size",
  "SENSING_OF_VOLUME": "volume",
  "SENSING_OF_BACKDROPNUMBER": "backdrop #",
  "SENSING_OF_BACKDROPNAME": "backdrop name",
  "SENSING_OF_STAGE": "Stage",
  "SENSING_CURRENT": "current %1",
  "SENSING_CURRENT_YEAR": "year",
  "SENSING_CURRENT_MONTH": "month",
  "SENSING_CURRENT_DATE": "date",
  "SENSING_CURRENT_DAYOFWEEK": "day of week",
  "SENSING_CURRENT_HOUR": "hour",
  "SENSING_CURRENT_MINUTE": "minute",
  "SENSING_CURRENT_SECOND": "second",
  "SENSING_DAYSSINCE2000": "days since 2000",
  "SENSING_USERNAME": "username",
  "SENSING_USERID": "user id",
  "SOUND_PLAY": "start sound %1",
  "SOUND_PLAYUNTILDONE": "play sound %1 until done",
  "SOUND_STOPALLSOUNDS": "stop all sounds",
  "SOUND_SETEFFECTO": "set %1 effect to %2",
  "SOUND_CHANGEEFFECTBY": "change %1 effect by %2",
  "SOUND_CLEAREFFECTS": "clear sound effects",
  "SOUND_EFFECTS_PITCH": "pitch",
  "SOUND_EFFECTS_PAN": "pan left/right",
  "SOUND_CHANGEVOLUMEBY": "change volume by %1",
  "SOUND_SETVOLUMETO": "set volume to %1%",
  "SOUND_VOLUME": "volume",
  "SOUND_RECORD": "record...",
  "CATEGORY_MOTION": "Motion",
  "CATEGORY_LOOKS": "Looks",
  "CATEGORY_SOUND": "Sound",
  "CATEGORY_EVENTS": "Events",
  "CATEGORY_CONTROL": "Control",
  "CATEGORY_SENSING": "Sensing",
  "CATEGORY_OPERATORS": "Operators",
  "CATEGORY_VARIABLES": "Variables",
  "CATEGORY_MYBLOCKS": "My Blocks",
  "DUPLICATE": "Duplicate",
  "DELETE": "Delete",
  "ADD_COMMENT": "Add Comment",
  "REMOVE_COMMENT": "Remove Comment",
  "DELETE_BLOCK": "Delete Block",
  "DELETE_X_BLOCKS": "Delete %1 Blocks",
  "DELETE_ALL_BLOCKS": "Delete all %1 blocks?",
  "CLEAN_UP": "Clean up Blocks",
  "HELP": "Help",
  "UNDO": "Undo",
  "REDO": "Redo",
  "FRAME": "Frame",
  "COLLAPSED_X_BLOCKS": "Collapsed %1 blocks",
  "COLOR": "Color",
  "CREATE_FRAME": "Create Frame",
  "EDIT_PROCEDURE": "Edit",
  "SHOW_PROCEDURE_DEFINITION": "Go to definition",
  "WORKSPACE_COMMENT_DEFAULT_TEXT": "Say something...",
  "COLOUR_HUE_LABEL": "Color",
  "COLOUR_SATURATION_LABEL": "Saturation",
  "COLOUR_BRIGHTNESS_LABEL": "Brightness",
  "CHANGE_VALUE_TITLE": "Change value:",
  "RENAME_VARIABLE": "Rename variable",
  "RENAME_VARIABLE_TITLE": "Rename all \"%1\" variables to:",
  "RENAME_VARIABLE_MODAL_TITLE": "Rename Variable",
  "NEW_VARIABLE": "Make a Variable",
  "NEW_VARIABLE_TITLE": "New variable name:",
  "VARIABLE_MODAL_TITLE": "New Variable",
  "VARIABLE_ALREADY_EXISTS": "A variable named \"%1\" already exists.",
  "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "A variable named \"%1\" already exists for another variable of type \"%2\".",
  "DELETE_VARIABLE_CONFIRMATION": "Delete %1 uses of the \"%2\" variable?",
  "CANNOT_DELETE_VARIABLE_PROCEDURE": "Can't delete the variable \"%1\" because it's part of the definition of the function \"%2\"",
  "DELETE_VARIABLE": "Delete the \"%1\" variable",
  "DISABLED_VARIABLE": 'This "%1" only can be deleted、rename in stage.',
  "VARIABLE": "variable",
  "LIST": "list",
  "NEW_PROCEDURE": "Make a Block",
  "PROCEDURE_ALREADY_EXISTS": "A procedure named \"%1\" already exists.",
  "PROCEDURE_DEFAULT_NAME": "block name",
  "PROCEDURE_USED": "To delete a block definition, first remove all uses of the block",
  "Global_PROCEDURE_USED": "To delete a block definition, first remove all uses of the block from sprite [%1]",
  "NEW_LIST": "Make a List",
  "NEW_LIST_TITLE": "New list name:",
  "LIST_MODAL_TITLE": "New List",
  "LIST_ALREADY_EXISTS": "A list named \"%1\" already exists.",
  "RENAME_LIST_TITLE": "Rename all \"%1\" lists to:",
  "RENAME_LIST_MODAL_TITLE": "Rename List",
  "DEFAULT_LIST_ITEM": "thing",
  "DELETE_LIST": "Delete the \"%1\" list",
  "RENAME_LIST": "Rename list",
  "NEW_BROADCAST_MESSAGE": "New message",
  "NEW_BROADCAST_MESSAGE_TITLE": "New message name:",
  "BROADCAST_MODAL_TITLE": "New Message",
  "DEFAULT_BROADCAST_MESSAGE_NAME": "message1",
  "PROCEDURE_RETURN": "return %1",
};

Blockly.ScratchMsgs.locales["ms"] =
{
  "CONTROL_FOREVER": "selamanya",
  "CONTROL_REPEAT": "ulangi %1 kali",
  "CONTROL_IF": "jika %1 maka",
  "CONTROL_ELSE": "lain",
  "CONTROL_STOP": "berhenti",
  "CONTROL_STOP_ALL": "semua",
  "CONTROL_STOP_THIS": "skrip ini",
  "CONTROL_STOP_OTHER": "skrip lain dalam sprite",
  "CONTROL_WAIT": "tunggu %1 saat",
  "CONTROL_WAITUNTIL": "tunggu sehingga %1",
  "CONTROL_REPEATUNTIL": "ulangi sehingga %1",
  "CONTROL_WHILE": "sementara %1",
  "CONTROL_FOREACH": "untuk setiap %1 dalam %2",
  "CONTROL_STARTASCLONE": "apabila saya mula sebagai klon",
  "CONTROL_CREATECLONEOF": "buat klon %1",
  "CONTROL_CREATECLONEOF_MYSELF": "diri saya",
  "CONTROL_DELETETHISCLONE": "padam klon ini",
  "CONTROL_COUNTER": "pengira",
  "CONTROL_INCRCOUNTER": "tambah pengira",
  "CONTROL_CLEARCOUNTER": "kosongkan pengira",
  "CONTROL_ALLATONCE": "semua sekaligus",
  "DATA_SETVARIABLETO": "set %1 kepada %2",
  "DATA_CHANGEVARIABLEBY": "ubah %1 dengan %2",
  "DATA_SHOWVARIABLE": "papar pembolehubah %1",
  "DATA_HIDEVARIABLE": "sembunyikan pembolehubah %1",
  "DATA_ADDTOLIST": "tambah %1 kepada %2",
  "DATA_DELETEOFLIST": "padam %1 daripada %2",
  "DATA_DELETEALLOFLIST": "padam semua daripada %1",
  "DATA_INSERTATLIST": "masukkan %1 di %2 dalam %3",
  "DATA_REPLACEITEMOFLIST": "gantikan item %1 dalam %2 dengan %3",
  "DATA_ITEMOFLIST": "item %1 dalam %2",
  "DATA_ITEMNUMOFLIST": "nombor item %1 dalam %2",
  "DATA_LENGTHOFLIST": "panjang %1",
  "DATA_LISTCONTAINSITEM": "%1 mengandungi %2?",
  "DATA_SHOWLIST": "papar senarai %1",
  "DATA_HIDELIST": "sembunyikan senarai %1",
  "DATA_INDEX_ALL": "semua",
  "DATA_INDEX_LAST": "terakhir",
  "DATA_INDEX_RANDOM": "rawak",
  "EVENT_WHENFLAGCLICKED": "apabila %1 diklik",
  "EVENT_WHENTHISSPRITECLICKED": "apabila sprite ini diklik",
  "EVENT_WHENSTAGECLICKED": "apabila latar belakang diklik",
  "EVENT_WHENTOUCHINGOBJECT": "apabila sprite ini menyentuh %1",
  "EVENT_WHENBROADCASTRECEIVED": "apabila saya menerima %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "apabila latar belakang bertukar kepada %1",
  "EVENT_WHENGREATERTHAN": "apabila %1 > %2",
  "EVENT_WHENGREATERTHAN_TIMER": "pemasa",
  "EVENT_WHENGREATERTHAN_LOUDNESS": "keras",
  "EVENT_BROADCAST": "siaran %1",
  "EVENT_BROADCASTANDWAIT": "siaran %1 dan tunggu",
  "EVENT_WHENKEYPRESSED": "apabila kekunci %1 ditekan",
  "EVENT_WHENKEYPRESSED_SPACE": "spasi",
  "EVENT_WHENKEYPRESSED_LEFT": "anak panah kiri",
  "EVENT_WHENKEYPRESSED_RIGHT": "anak panah kanan",
  "EVENT_WHENKEYPRESSED_DOWN": "anak panah bawah",
  "EVENT_WHENKEYPRESSED_UP": "anak panah atas",
  "EVENT_WHENKEYPRESSED_ANY": "mana-mana",
  "LOOKS_SAYFORSECS": "katakan %1 selama %2 saat",
  "LOOKS_SAY": "katakan %1",
  "LOOKS_HELLO": "Halo!",
  "LOOKS_THINKFORSECS": "fikir %1 selama %2 saat",
  "LOOKS_THINK": "fikir %1",
  "LOOKS_HMM": "Hmm...",
  "LOOKS_SHOW": "tunjukkan",
  "LOOKS_HIDE": "sembunyikan",
  "LOOKS_HIDEALLSPRITES": "sembunyikan semua sprite",
  "LOOKS_EFFECT_COLOR": "warna",
  "LOOKS_EFFECT_FISHEYE": "mata ikan",
  "LOOKS_EFFECT_WHIRL": "pusar",
  "LOOKS_EFFECT_PIXELATE": "pixelate",
  "LOOKS_EFFECT_MOSAIC": "mosaik",
  "LOOKS_EFFECT_BRIGHTNESS": "kecerahan",
  "LOOKS_EFFECT_GHOST": "hantu",
  "LOOKS_CHANGEEFFECTBY": "ubah %1 kesan dengan %2",
  "LOOKS_SETEFFECTTO": "set %1 kesan kepada %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "padam kesan grafik",
  "LOOKS_CHANGESIZEBY": "ubah saiz dengan %1",
  "LOOKS_SETSIZETO": "set saiz kepada %1 %",
  "LOOKS_SIZE": "saiz",
  "LOOKS_CHANGESTRETCHBY": "ubah regangan dengan %1",
  "LOOKS_SETSTRETCHTO": "set regangan kepada %1 %",
  "LOOKS_SWITCHCOSTUMETO": "tukar kostum kepada %1",
  "LOOKS_NEXTCOSTUME": "kostum seterusnya",
  "LOOKS_SWITCHBACKDROPTO": "tukar latar belakang kepada %1",
  "LOOKS_GOTOFRONTBACK": "pergi ke lapisan %1",
  "LOOKS_GOTOFRONTBACK_FRONT": "hadapan",
  "LOOKS_GOTOFRONTBACK_BACK": "belakang",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "pergi %1 %2 lapisan",
  "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "ke hadapan",
  "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "ke belakang",
  "LOOKS_BACKDROPNUMBERNAME": "latar belakang %1",
  "LOOKS_COSTUMENUMBERNAME": "kostum %1",
  "LOOKS_NUMBERNAME_NUMBER": "nombor",
  "LOOKS_NUMBERNAME_NAME": "nama",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "tukar latar belakang kepada %1 dan tunggu",
  "LOOKS_NEXTBACKDROP_BLOCK": "latar belakang seterusnya",
  "LOOKS_NEXTBACKDROP": "latar belakang seterusnya",
  "LOOKS_PREVIOUSBACKDROP": "latar belakang sebelumnya",
  "LOOKS_RANDOMBACKDROP": "latar belakang rawak",
  "MOTION_MOVESTEPS": "gerak %1 langkah",
  "MOTION_TURNLEFT": "pusing %1 %2 darjah",
  "MOTION_TURNRIGHT": "pusing %1 %2 darjah",
  "MOTION_POINTINDIRECTION": "arah ke arah %1",
  "MOTION_POINTTOWARDS": "arah ke arah %1",
  "MOTION_POINTTOWARDS_POINTER": "penunjuk tetikus",
  "MOTION_POINTTOWARDS_RANDOM": "arah rawak",
  "MOTION_GOTO": "pergi ke %1",
  "MOTION_GOTO_POINTER": "penunjuk tetikus",
  "MOTION_GOTO_RANDOM": "posisi rawak",
  "MOTION_GOTOXY": "pergi ke x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "meluncur %1 saat ke x: %2 y: %3",
  "MOTION_GLIDETO": "meluncur %1 saat ke %2",
  "MOTION_GLIDETO_POINTER": "penunjuk tetikus",
  "MOTION_GLIDETO_RANDOM": "posisi rawak",
  "MOTION_CHANGEXBY": "ubah x dengan %1",
  "MOTION_SETX": "set x kepada %1",
  "MOTION_CHANGEYBY": "ubah y dengan %1",
  "MOTION_SETY": "set y kepada %1",
  "MOTION_IFONEDGEBOUNCE": "jika di tepi, pantulkan",
  "MOTION_SETROTATIONSTYLE": "set gaya putaran kepada %1",
  "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "kiri-kanan",
  "MOTION_SETROTATIONSTYLE_DONTROTATE": "jangan putar",
  "MOTION_SETROTATIONSTYLE_ALLAROUND": "sekeliling",
  "MOTION_XPOSITION": "posisi x",
  "MOTION_YPOSITION": "posisi y",
  "MOTION_DIRECTION": "arah",
  "MOTION_SCROLLRIGHT": "gelongsor ke kanan %1",
  "MOTION_SCROLLUP": "gelongsor ke atas %1",
  "MOTION_ALIGNSCENE": "sejajarkan adegan %1",
  "MOTION_ALIGNSCENE_BOTTOMLEFT": "bawah-kiri",
  "MOTION_ALIGNSCENE_BOTTOMRIGHT": "bawah-kanan",
  "MOTION_ALIGNSCENE_MIDDLE": "tengah",
  "MOTION_ALIGNSCENE_TOPLEFT": "atas-kiri",
  "MOTION_ALIGNSCENE_TOPRIGHT": "atas-kanan",
  "MOTION_XSCROLL": "gelongsor x",
  "MOTION_YSCROLL": "gelongsor y",
  "MOTION_STAGE_SELECTED": "Adegan dipilih: tiada blok gerakan",
  "MOTION_MOVEGRIDS": "gerak %1 grid (40 langkah)",
  "OPERATORS_ADD": "%1 + %2",
  "OPERATORS_SUBTRACT": "%1 - %2",
  "OPERATORS_MULTIPLY": "%1 * %2",
  "OPERATORS_DIVIDE": "%1 / %2",
  "OPERATORS_RANDOM": "pilih rawak %1 hingga %2",
  "OPERATORS_GT": "%1 > %2",
  "OPERATORS_LT": "%1 < %2",
  "OPERATORS_EQUALS": "%1 = %2",
  "OPERATORS_AND": "%1 dan %2",
  "OPERATORS_OR": "%1 atau %2",
  "OPERATORS_NOT": "bukan %1",
  "OPERATORS_JOIN": "gabung %1 %2",
  "OPERATORS_JOIN_APPLE": "epal",
  "OPERATORS_JOIN_BANANA": "pisang",
  "OPERATORS_LETTEROF": "huruf %1 dalam %2",
  "OPERATORS_LETTEROF_APPLE": "a",
  "OPERATORS_LENGTH": "panjang %1",
  "OPERATORS_CONTAINS": "%1 mengandungi %2?",
  "OPERATORS_MOD": "%1 mod %2",
  "OPERATORS_ROUND": "pusing %1",
  "OPERATORS_MATHOP": "%1 daripada %2",
  "OPERATORS_MATHOP_ABS": "abs",
  "OPERATORS_MATHOP_FLOOR": "lantai",
  "OPERATORS_MATHOP_CEILING": "langit-langit",
  "OPERATORS_MATHOP_SQRT": "sqrt",
  "OPERATORS_MATHOP_SIN": "sin",
  "OPERATORS_MATHOP_COS": "cos",
  "OPERATORS_MATHOP_TAN": "tan",
  "OPERATORS_MATHOP_ASIN": "asin",
  "OPERATORS_MATHOP_ACOS": "acos",
  "OPERATORS_MATHOP_ATAN": "atan",
  "OPERATORS_MATHOP_LN": "ln",
  "OPERATORS_MATHOP_LOG": "log",
  "OPERATORS_MATHOP_EEXP": "e ^",
  "OPERATORS_MATHOP_10EXP": "10 ^",
  "PROCEDURES_DEFINITION": "definisi %1",
  "SENSING_TOUCHINGOBJECT": "menyentuh %1?",
  "SENSING_TOUCHINGOBJECT_POINTER": "penunjuk tetikus",
  "SENSING_TOUCHINGOBJECT_EDGE": "tepi",
  "SENSING_TOUCHINGCOLOR": "menyentuh warna %1?",
  "SENSING_COLORISTOUCHINGCOLOR": "warna %1 menyentuh %2?",
  "SENSING_DISTANCETO": "jarak ke %1",
  "SENSING_DISTANCETO_POINTER": "penunjuk tetikus",
  "SENSING_ASKANDWAIT": "tanya %1 dan tunggu",
  "SENSING_ASK_TEXT": "Siapa nama anda?",
  "SENSING_ANSWER": "jawapan",
  "SENSING_KEYPRESSED": "kekunci %1 ditekan?",
  "SENSING_MOUSEDOWN": "tetikus ke bawah?",
  "SENSING_MOUSEX": "tetikus x",
  "SENSING_MOUSEY": "tetikus y",
  "SENSING_SETDRAGMODE": "set mod tarik %1",
  "SENSING_SETDRAGMODE_DRAGGABLE": "boleh tarik",
  "SENSING_SETDRAGMODE_NOTDRAGGABLE": "tidak boleh tarik",
  "SENSING_LOUDNESS": "kelakaran",
  "SENSING_LOUD": "keras?",
  "SENSING_TIMER": "pemasa",
  "SENSING_RESETTIMER": "reset pemasa",
  "SENSING_OF": "%1 daripada %2",
  "SENSING_OF_XPOSITION": "posisi x",
  "SENSING_OF_YPOSITION": "posisi y",
  "SENSING_OF_DIRECTION": "arah",
  "SENSING_OF_COSTUMENUMBER": "nombor kostum",
  "SENSING_OF_COSTUMENAME": "nama kostum",
  "SENSING_OF_SIZE": "saiz",
  "SENSING_OF_VOLUME": "kelakaran",
  "SENSING_OF_BACKDROPNUMBER": "nombor latar belakang",
  "SENSING_OF_BACKDROPNAME": "nama latar belakang",
  "SENSING_OF_STAGE": "Peringkat",
  "SENSING_CURRENT": "%1 semasa",
  "SENSING_CURRENT_YEAR": "tahun",
  "SENSING_CURRENT_MONTH": "bulan",
  "SENSING_CURRENT_DATE": "tarikh",
  "SENSING_CURRENT_DAYOFWEEK": "hari dalam minggu",
  "SENSING_CURRENT_HOUR": "jam",
  "SENSING_CURRENT_MINUTE": "minit",
  "SENSING_CURRENT_SECOND": "saat",
  "SENSING_DAYSSINCE2000": "hari sejak 2000",
  "SENSING_USERNAME": "nama pengguna",
  "SENSING_USERID": "ID pengguna",
  "SOUND_PLAY": "mulakan bunyi %1",
  "SOUND_PLAYUNTILDONE": "mainkan bunyi %1 sehingga selesai",
  "SOUND_STOPALLSOUNDS": "hentikan semua bunyi",
  "SOUND_SETEFFECTO": "set %1 kesan kepada %2",
  "SOUND_CHANGEEFFECTBY": "ubah %1 kesan dengan %2",
  "SOUND_CLEAREFFECTS": "padam kesan bunyi",
  "SOUND_EFFECTS_PITCH": "puncak",
  "SOUND_EFFECTS_PAN": "pusing kiri/kanan",
  "SOUND_CHANGEVOLUMEBY": "ubah kelakaran dengan %1",
  "SOUND_SETVOLUMETO": "set kelakaran kepada %1%",
  "SOUND_VOLUME": "kelakaran",
  "SOUND_RECORD": "rakam...",
  "CATEGORY_MOTION": "Gerakan",
  "CATEGORY_LOOKS": "Rupa",
  "CATEGORY_SOUND": "Bunyi",
  "CATEGORY_EVENTS": "Peristiwa",
  "CATEGORY_CONTROL": "Kawalan",
  "CATEGORY_SENSING": "Pengecaman",
  "CATEGORY_OPERATORS": "Pengendali",
  "CATEGORY_VARIABLES": "Pembolehubah",
  "CATEGORY_MYBLOCKS": "Bloku Saya",
  "DUPLICATE": "Duplikat",
  "DELETE": "Padam",
  "ADD_COMMENT": "Tambah Komen",
  "REMOVE_COMMENT": "Padam Komen",
  "DELETE_BLOCK": "Padam Blok",
  "DELETE_X_BLOCKS": "Padam %1 Blok",
  "DELETE_ALL_BLOCKS": "Padam semua %1 blok?",
  "CLEAN_UP": "Bersihkan Blok",
  "HELP": "Bantuan",
  "UNDO": "Undo",
  "REDO": "Redo",
  "FRAME": "Bingkai",
  "COLLAPSED_X_BLOCKS": "Blok Dijatuhkan %1",
  "COLOR": "Warna",
  "CREATE_FRAME": "Cipta Bingkai",
  "EDIT_PROCEDURE": "Edit",
  "SHOW_PROCEDURE_DEFINITION": "Pergi ke definisi",
  "WORKSPACE_COMMENT_DEFAULT_TEXT": "Kata sesuatu...",
  "COLOUR_HUE_LABEL": "Warna",
  "COLOUR_SATURATION_LABEL": "Saturasi",
  "COLOUR_BRIGHTNESS_LABEL": "Kecerahan",
  "CHANGE_VALUE_TITLE": "Ubah nilai:",
  "RENAME_VARIABLE": "Tukar nama pemboleh ubah",
  "RENAME_VARIABLE_TITLE": "Tukar nama semua pemboleh ubah \"%1\" kepada:",
  "RENAME_VARIABLE_MODAL_TITLE": "Tukar Nama Pemboleh Ubah",
  "NEW_VARIABLE": "Buat Pemboleh Ubah",
  "NEW_VARIABLE_TITLE": "Nama pemboleh ubah baru:",
  "VARIABLE_MODAL_TITLE": "Pemboleh Ubah Baru",
  "VARIABLE_ALREADY_EXISTS": "Sebuah pemboleh ubah bernama \"%1\" sudah wujud.",
  "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "Sebuah pemboleh ubah bernama \"%1\" sudah wujud untuk pemboleh ubah yang lain jenis \"%2\".",
  "DELETE_VARIABLE_CONFIRMATION": "Padam %1 penggunaan pemboleh ubah \"%2\"?",
  "CANNOT_DELETE_VARIABLE_PROCEDURE": "Tidak boleh padam pemboleh ubah \"%1\" kerana ia merupakan sebahagian daripada definisi fungsi \"%2\"",
  "DELETE_VARIABLE": "Padam pemboleh ubah \"%1\"",
  "DISABLED_VARIABLE": 'Ini "%1" hanya boleh dipadam、ditukar nama dalam peringkat.',
  "VARIABLE": "pemboleh ubah",
  "LIST": "senarai",
  "NEW_PROCEDURE": "Buat Blok",
  "PROCEDURE_ALREADY_EXISTS": "Sebuah blok bernama \"%1\" sudah wujud.",
  "PROCEDURE_DEFAULT_NAME": "nama blok",
  "PROCEDURE_USED": "Untuk memadam definisi blok, pertama-tama alihkan semua penggunaan blok",
  "Global_PROCEDURE_USED": "Untuk memadam definisi blok, pertama-tama alihkan semua penggunaan blok dari sprite [%1]",
  "NEW_LIST": "Buat Senarai",
  "NEW_LIST_TITLE": "Nama senarai baru:",
  "LIST_MODAL_TITLE": "Senarai Baru",
  "LIST_ALREADY_EXISTS": "Sebuah senarai bernama \"%1\" sudah wujud.",
  "RENAME_LIST_TITLE": "Tukar nama semua senarai \"%1\" kepada:",
  "RENAME_LIST_MODAL_TITLE": "Tukar Nama Senarai",
  "DEFAULT_LIST_ITEM": "benda",
  "DELETE_LIST": "Padam senarai \"%1\"",
  "RENAME_LIST": "Tukar nama senarai",
  "NEW_BROADCAST_MESSAGE": "Mesej Baru",
  "NEW_BROADCAST_MESSAGE_TITLE": "Nama mesej baru:",
  "BROADCAST_MODAL_TITLE": "Mesej Baru",
  "DEFAULT_BROADCAST_MESSAGE_NAME": "mesej1",
  "PROCEDURE_RETURN": "kembali %1"
};

Blockly.ScratchMsgs.locales["ru"] =
{
  "CONTROL_FOREVER": "повторять всегда",
  "CONTROL_REPEAT": "повторить %1 раз",
  "CONTROL_IF": "если %1 , то",
  "CONTROL_ELSE": "иначе",
  "CONTROL_STOP": "стоп",
  "CONTROL_STOP_ALL": "все",
  "CONTROL_STOP_THIS": "этот скрипт",
  "CONTROL_STOP_OTHER": "другие скрипты спрайта",
  "CONTROL_WAIT": "ждать %1 секунд",
  "CONTROL_WAITUNTIL": "ждать до %1",
  "CONTROL_REPEATUNTIL": "повторять пока не %1",
  "CONTROL_WHILE": "пока %1",
  "CONTROL_FOREACH": "для каждого %1 в %2",
  "CONTROL_STARTASCLONE": "когда я начинаю как клон",
  "CONTROL_CREATECLONEOF": "создать клон %1",
  "CONTROL_CREATECLONEOF_MYSELF": "самого себя",
  "CONTROL_DELETETHISCLONE": "удалить клон",
  "CONTROL_COUNTER": "счётчик",
  "CONTROL_INCRCOUNTER": "увеличить счётчик",
  "CONTROL_CLEARCOUNTER": "очистить счётчик",
  "CONTROL_ALLATONCE": "все сразу",
  "DATA_SETVARIABLETO": "задать %1 значение %2",
  "DATA_CHANGEVARIABLEBY": "изменить %1 на %2",
  "DATA_SHOWVARIABLE": "показать переменную %1",
  "DATA_HIDEVARIABLE": "скрыть переменную %1",
  "DATA_ADDTOLIST": "добавить %1 к %2",
  "DATA_DELETEOFLIST": "удалить %1 из %2",
  "DATA_DELETEALLOFLIST": "удалить все из %1",
  "DATA_INSERTATLIST": "вставить %1 в %3 из %2",
  "DATA_REPLACEITEMOFLIST": "заменить элемент %1 в %2 на %3",
  "DATA_ITEMOFLIST": "элемент %1 в %2",
  "DATA_ITEMNUMOFLIST": "№ элемента %1 в %2",
  "DATA_LENGTHOFLIST": "длина списка %1",
  "DATA_LISTCONTAINSITEM": "%1 содержит %2?",
  "DATA_SHOWLIST": "показать список %1",
  "DATA_HIDELIST": "скрыть список %1",
  "DATA_INDEX_ALL": "все",
  "DATA_INDEX_LAST": "последний",
  "DATA_INDEX_RANDOM": "случайный",
  "EVENT_WHENFLAGCLICKED": "когда %1 нажат",
  "EVENT_WHENTHISSPRITECLICKED": "когда спрайт нажат",
  "EVENT_WHENSTAGECLICKED": "когда кликнут по сцене",
  "EVENT_WHENTOUCHINGOBJECT": "когда этот спрайт касается %1",
  "EVENT_WHENBROADCASTRECEIVED": "когда я получу %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "когда фон сменился на %1",
  "EVENT_WHENGREATERTHAN": "когда %1 > %2",
  "EVENT_WHENGREATERTHAN_TIMER": "таймер",
  "EVENT_WHENGREATERTHAN_LOUDNESS": "громкость",
  "EVENT_BROADCAST": "передать %1",
  "EVENT_BROADCASTANDWAIT": "передать %1 и ждать до конца",
  "EVENT_WHENKEYPRESSED": "когда клавиша %1 нажата",
  "EVENT_WHENKEYPRESSED_SPACE": "пробел",
  "EVENT_WHENKEYPRESSED_LEFT": "стрелка влево",
  "EVENT_WHENKEYPRESSED_RIGHT": "стрелка вправо",
  "EVENT_WHENKEYPRESSED_DOWN": "стрелка вниз",
  "EVENT_WHENKEYPRESSED_UP": "стрелка вверх",
  "EVENT_WHENKEYPRESSED_ANY": "любая",
  "LOOKS_SAYFORSECS": "говорить %1 %2 секунд",
  "LOOKS_SAY": "сказать %1",
  "LOOKS_HELLO": "Привет!",
  "LOOKS_THINKFORSECS": "думать %1 %2 секунд",
  "LOOKS_THINK": "думать %1",
  "LOOKS_HMM": "М-м-м...",
  "LOOKS_SHOW": "показаться",
  "LOOKS_HIDE": "спрятаться",
  "LOOKS_HIDEALLSPRITES": "спрятать все спрайты",
  "LOOKS_EFFECT_COLOR": "цвет",
  "LOOKS_EFFECT_FISHEYE": "рыбий глаз",
  "LOOKS_EFFECT_WHIRL": "завихрение",
  "LOOKS_EFFECT_PIXELATE": "укрупнение пикселей",
  "LOOKS_EFFECT_MOSAIC": "мозаика",
  "LOOKS_EFFECT_BRIGHTNESS": "яркость",
  "LOOKS_EFFECT_GHOST": "прозрачность",
  "LOOKS_CHANGEEFFECTBY": "изменить эффект %1 на %2",
  "LOOKS_SETEFFECTTO": "установить эффект %1 %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "убрать графические эффекты",
  "LOOKS_CHANGESIZEBY": "изменить размер на %1 %",
  "LOOKS_SETSIZETO": "установить размер %1 %",
  "LOOKS_SIZE": "размер",
  "LOOKS_CHANGESTRETCHBY": "изменить натяжение на %1",
  "LOOKS_SETSTRETCHTO": "установить натяжение %1 %",
  "LOOKS_SWITCHCOSTUMETO": "изменить костюм на %1",
  "LOOKS_NEXTCOSTUME": "следующий костюм",
  "LOOKS_SWITCHBACKDROPTO": "переключить фон на %1",
  "LOOKS_GOTOFRONTBACK": "перейти на %1 слой",
  "LOOKS_GOTOFRONTBACK_FRONT": "передний",
  "LOOKS_GOTOFRONTBACK_BACK": "задний",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "перейти %1 на %2 слоя",
  "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "вперёд",
  "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "назад",
  "LOOKS_BACKDROPNUMBERNAME": "фон %1",
  "LOOKS_COSTUMENUMBERNAME": "костюм %1",
  "LOOKS_NUMBERNAME_NUMBER": "номер",
  "LOOKS_NUMBERNAME_NAME": "имя",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "переключить фон на %1 и ждать",
  "LOOKS_NEXTBACKDROP_BLOCK": "следующий фон",
  "LOOKS_NEXTBACKDROP": "следующий фон",
  "LOOKS_PREVIOUSBACKDROP": "предыдущий фон",
  "LOOKS_RANDOMBACKDROP": "случайный фон",
  "MOTION_MOVESTEPS": "идти %1 шагов",
  "MOTION_TURNLEFT": "повернуть %1 на %2 градусов",
  "MOTION_TURNRIGHT": "повернуть %1 на %2 градусов",
  "MOTION_POINTINDIRECTION": "повернуться в направлении %1",
  "MOTION_POINTTOWARDS": "повернуться к %1",
  "MOTION_POINTTOWARDS_POINTER": "указатель мыши",
  "MOTION_POINTTOWARDS_RANDOM": "случайно направление",
  "MOTION_GOTO": "перейти на %1",
  "MOTION_GOTO_POINTER": "указатель мыши",
  "MOTION_GOTO_RANDOM": "случайное положение",
  "MOTION_GOTOXY": "перейти в x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "плыть %1 секунд в точку x: %2 y: %3",
  "MOTION_GLIDETO": "плыть %1 секунд к %2",
  "MOTION_GLIDETO_POINTER": "указатель мыши",
  "MOTION_GLIDETO_RANDOM": "случайное положение",
  "MOTION_CHANGEXBY": "изменить x на %1",
  "MOTION_SETX": "установить x в %1",
  "MOTION_CHANGEYBY": "изменить y на %1",
  "MOTION_SETY": "установить y в %1",
  "MOTION_IFONEDGEBOUNCE": "если касается края, оттолкнуться",
  "MOTION_SETROTATIONSTYLE": "установить способ вращения %1",
  "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "влево-вправо",
  "MOTION_SETROTATIONSTYLE_DONTROTATE": "не вращать",
  "MOTION_SETROTATIONSTYLE_ALLAROUND": "кругом",
  "MOTION_XPOSITION": "положение x",
  "MOTION_YPOSITION": "положение y",
  "MOTION_DIRECTION": "направление",
  "MOTION_SCROLLRIGHT": "прокрутить вправо %1",
  "MOTION_SCROLLUP": "прокрутить вверх %1",
  "MOTION_ALIGNSCENE": "выровнять сцену %1",
  "MOTION_ALIGNSCENE_BOTTOMLEFT": "нижний левый",
  "MOTION_ALIGNSCENE_BOTTOMRIGHT": "нижний правый",
  "MOTION_ALIGNSCENE_MIDDLE": "середина",
  "MOTION_ALIGNSCENE_TOPLEFT": "верхний левый",
  "MOTION_ALIGNSCENE_TOPRIGHT": "верхний правый",
  "MOTION_XSCROLL": "x прокрутка",
  "MOTION_YSCROLL": "y прокрутка",
  "MOTION_STAGE_SELECTED": "Выбрана сцена: нет блоков движения",
  "MOTION_MOVEGRIDS": "переместить %1 сеток (40 шагов)",
  "OPERATORS_ADD": "%1 + %2",
  "OPERATORS_SUBTRACT": "%1 - %2",
  "OPERATORS_MULTIPLY": "%1 * %2",
  "OPERATORS_DIVIDE": "%1 / %2",
  "OPERATORS_RANDOM": "выдать случайное от %1 до %2",
  "OPERATORS_GT": "%1 > %2",
  "OPERATORS_LT": "%1 < %2",
  "OPERATORS_EQUALS": "%1 = %2",
  "OPERATORS_AND": "%1 и %2",
  "OPERATORS_OR": "%1 или %2",
  "OPERATORS_NOT": "не %1",
  "OPERATORS_JOIN": "объединить %1 %2",
  "OPERATORS_JOIN_APPLE": "яблоко",
  "OPERATORS_JOIN_BANANA": "банан",
  "OPERATORS_LETTEROF": "буква %1 в %2",
  "OPERATORS_LETTEROF_APPLE": "а",
  "OPERATORS_LENGTH": "длина %1",
  "OPERATORS_CONTAINS": "%1 содержит %2?",
  "OPERATORS_MOD": "%1 mod %2",
  "OPERATORS_ROUND": "округлить %1",
  "OPERATORS_MATHOP": "%1 от %2",
  "OPERATORS_MATHOP_ABS": "модуль",
  "OPERATORS_MATHOP_FLOOR": "целое меньшее",
  "OPERATORS_MATHOP_CEILING": "целое большее",
  "OPERATORS_MATHOP_SQRT": "квадратный корень",
  "OPERATORS_MATHOP_SIN": "sin",
  "OPERATORS_MATHOP_COS": "cos",
  "OPERATORS_MATHOP_TAN": "tan",
  "OPERATORS_MATHOP_ASIN": "asin",
  "OPERATORS_MATHOP_ACOS": "acos",
  "OPERATORS_MATHOP_ATAN": "atan",
  "OPERATORS_MATHOP_LN": "ln",
  "OPERATORS_MATHOP_LOG": "log",
  "OPERATORS_MATHOP_EEXP": "e ^",
  "OPERATORS_MATHOP_10EXP": "10 ^",
  "PROCEDURES_DEFINITION": "определить %1",
  "SENSING_TOUCHINGOBJECT": "касается %1?",
  "SENSING_TOUCHINGOBJECT_POINTER": "указатель мыши",
  "SENSING_TOUCHINGOBJECT_EDGE": "край",
  "SENSING_TOUCHINGCOLOR": "касается цвета %1?",
  "SENSING_COLORISTOUCHINGCOLOR": "цвет %1 касается цвета %2?",
  "SENSING_DISTANCETO": "расстояние до %1",
  "SENSING_DISTANCETO_POINTER": "указатель мыши",
  "SENSING_ASKANDWAIT": "спросить %1 и ждать",
  "SENSING_ASK_TEXT": "Как тебя зовут?",
  "SENSING_ANSWER": "ответ",
  "SENSING_KEYPRESSED": "клавиша %1 нажата?",
  "SENSING_MOUSEDOWN": "мышь нажата?",
  "SENSING_MOUSEX": "x мыши",
  "SENSING_MOUSEY": "y мыши",
  "SENSING_SETDRAGMODE": "перетаскивать %1",
  "SENSING_SETDRAGMODE_DRAGGABLE": "можно",
  "SENSING_SETDRAGMODE_NOTDRAGGABLE": "нельзя",
  "SENSING_LOUDNESS": "громкость",
  "SENSING_LOUD": "громко?",
  "SENSING_TIMER": "таймер",
  "SENSING_RESETTIMER": "сбросить таймер",
  "SENSING_OF": "%1 от %2",
  "SENSING_OF_XPOSITION": "положение x",
  "SENSING_OF_YPOSITION": "положение y",
  "SENSING_OF_DIRECTION": "направление",
  "SENSING_OF_COSTUMENUMBER": "костюм #",
  "SENSING_OF_COSTUMENAME": "имя костюма",
  "SENSING_OF_SIZE": "размер",
  "SENSING_OF_VOLUME": "громкость",
  "SENSING_OF_BACKDROPNUMBER": "фон #",
  "SENSING_OF_BACKDROPNAME": "имя фона",
  "SENSING_OF_STAGE": "Сцена",
  "SENSING_CURRENT": "текущий %1",
  "SENSING_CURRENT_YEAR": "год",
  "SENSING_CURRENT_MONTH": "месяц",
  "SENSING_CURRENT_DATE": "дата",
  "SENSING_CURRENT_DAYOFWEEK": "день недели",
  "SENSING_CURRENT_HOUR": "час",
  "SENSING_CURRENT_MINUTE": "минута",
  "SENSING_CURRENT_SECOND": "секунда",
  "SENSING_DAYSSINCE2000": "дней с 2000 г",
  "SENSING_USERNAME": "имя пользователя",
  "SENSING_USERID": "id пользователя",
  "SOUND_PLAY": "включить звук %1",
  "SOUND_PLAYUNTILDONE": "играть звук %1 до конца",
  "SOUND_STOPALLSOUNDS": "остановить все звуки",
  "SOUND_SETEFFECTO": "установить эффект %1 в %2",
  "SOUND_CHANGEEFFECTBY": "изменить %1 эффект на %2",
  "SOUND_CLEAREFFECTS": "убрать звуковые эффекты",
  "SOUND_EFFECTS_PITCH": "высота тона",
  "SOUND_EFFECTS_PAN": "звучание слева/справа",
  "SOUND_CHANGEVOLUMEBY": "изменить громкость на %1",
  "SOUND_SETVOLUMETO": "установить громкость %1%",
  "SOUND_VOLUME": "громкость звука",
  "SOUND_RECORD": "запись…",
  "CATEGORY_MOTION": "Движение",
  "CATEGORY_LOOKS": "Внешний вид",
  "CATEGORY_SOUND": "Звук",
  "CATEGORY_EVENTS": "События",
  "CATEGORY_CONTROL": "Управление",
  "CATEGORY_SENSING": "Сенсоры",
  "CATEGORY_OPERATORS": "Операторы",
  "CATEGORY_VARIABLES": "Переменные",
  "CATEGORY_MYBLOCKS": "Другие блоки",
  "DUPLICATE": "Дублировать",
  "DELETE": "Удалить",
  "ADD_COMMENT": "Добавить комментарий",
  "REMOVE_COMMENT": "Удалить комментарий",
  "DELETE_BLOCK": "Удалить блок",
  "DELETE_X_BLOCKS": "Удалить %1 блоки",
  "DELETE_ALL_BLOCKS": "Удалить все %1 блоки?",
  "CLEAN_UP": "Очистить блоки",
  "HELP": "Помощь",
  "UNDO": "Отменить",
  "REDO": "Вернуть",
  "FRAME": "Кадр",
  "CREATE_FRAME": "Создать Кадр",
  "COLLAPSED_X_BLOCKS": "Свернуто %1 блоков",
  "COLOR": "Цвет",
  "EDIT_PROCEDURE": "Редактировать",
  "SHOW_PROCEDURE_DEFINITION": "Перейти к определению",
  "WORKSPACE_COMMENT_DEFAULT_TEXT": "Скажи что-нибудь...",
  "COLOUR_HUE_LABEL": "Цвет",
  "COLOUR_SATURATION_LABEL": "Насыщенность",
  "COLOUR_BRIGHTNESS_LABEL": "Яркость",
  "CHANGE_VALUE_TITLE": "Изменить значение:",
  "RENAME_VARIABLE": "Переименовать переменную",
  "RENAME_VARIABLE_TITLE": "Переименовать все \"%1\" переменных в:",
  "RENAME_VARIABLE_MODAL_TITLE": "Переименовать переменную",
  "NEW_VARIABLE": "Создать переменную",
  "NEW_VARIABLE_TITLE": "Имя новой переменной:",
  "VARIABLE_MODAL_TITLE": "Новая переменная",
  "VARIABLE_ALREADY_EXISTS": "Переменная с именем \"%1\" уже существует.",
  "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "переменная с именем \"%1\" уже существует в другом типе переменных \"%2\".",
  "DELETE_VARIABLE_CONFIRMATION": "Удалить %1 использований  \"%2\" переменной?",
  "CANNOT_DELETE_VARIABLE_PROCEDURE": "Нельзя удалить переменную \"%1\", так как она является частью определения функции \"%2\"",
  "DELETE_VARIABLE": "Удалить переменную \"%1\"",
  "DISABLED_VARIABLE": 'Этот "%1" можно удалить или переименовать только на сцене.',
  "VARIABLE": "переменная",
  "LIST": "список",
  "NEW_PROCEDURE": "Создать блок",
  "PROCEDURE_ALREADY_EXISTS": "Процедура с именем \"%1\" уже существует.",
  "PROCEDURE_DEFAULT_NAME": "название блока",
  "PROCEDURE_USED": "Прежде чем удалить блок, удалите все случаи его использования.",
  "Global_PROCEDURE_USED": "Чтобы удалить определение блока, сначала удалите все использования блока из спрайта [%1]",
  "NEW_LIST": "Создать список",
  "NEW_LIST_TITLE": "Имя нового списка:",
  "LIST_MODAL_TITLE": "Новый список",
  "LIST_ALREADY_EXISTS": "Список с именем \"%1\" уже существует.",
  "RENAME_LIST_TITLE": "Переименовать все \"%1\" списки в:",
  "RENAME_LIST_MODAL_TITLE": "Переименовать список",
  "DEFAULT_LIST_ITEM": "что-то",
  "DELETE_LIST": "Удалить список \"%1\"",
  "RENAME_LIST": "Переименовать список",
  "NEW_BROADCAST_MESSAGE": "Новое сообщение",
  "NEW_BROADCAST_MESSAGE_TITLE": "Новое имя сообщения:",
  "BROADCAST_MODAL_TITLE": "Новое сообщение",
  "DEFAULT_BROADCAST_MESSAGE_NAME": "сообщение1",
  "PROCEDURE_RETURN": "вернуть %1",
};

Blockly.ScratchMsgs.locales["uk"] =
{
  "CONTROL_FOREVER": "завжди",
  "CONTROL_REPEAT": "повторити %1",
  "CONTROL_IF": "якщо %1 то",
  "CONTROL_ELSE": "інакше",
  "CONTROL_STOP": "зупинити",
  "CONTROL_STOP_ALL": "все",
  "CONTROL_STOP_THIS": "цей скрипт",
  "CONTROL_STOP_OTHER": "інші скрипти цього спрайту",
  "CONTROL_WAIT": "чекати %1 секунд",
  "CONTROL_WAITUNTIL": "чекати поки %1",
  "CONTROL_REPEATUNTIL": "повторити до %1",
  "CONTROL_WHILE": "поки %1",
  "CONTROL_FOREACH": "для кожного %1 в %2",
  "CONTROL_STARTASCLONE": "коли я починаю як клон",
  "CONTROL_CREATECLONEOF": "створити клон з %1",
  "CONTROL_CREATECLONEOF_MYSELF": "мене",
  "CONTROL_DELETETHISCLONE": "вилучити цей клон",
  "CONTROL_COUNTER": "лічильник",
  "CONTROL_INCRCOUNTER": "збільшити лічильник",
  "CONTROL_CLEARCOUNTER": "очистити лічильник",
  "CONTROL_ALLATONCE": "всі одночасно",
  "DATA_SETVARIABLETO": "надати %1 значення %2",
  "DATA_CHANGEVARIABLEBY": "змінити %1 на %2",
  "DATA_SHOWVARIABLE": "показати змінну %1",
  "DATA_HIDEVARIABLE": "сховати змінну %1",
  "DATA_ADDTOLIST": "додати %1 до %2",
  "DATA_DELETEOFLIST": "вилучити %1 з %2",
  "DATA_DELETEALLOFLIST": "вилучити все з %1",
  "DATA_INSERTATLIST": "вставити %1 на місці %2 списку %3",
  "DATA_REPLACEITEMOFLIST": "замінити елемент %1 в %2 на %3",
  "DATA_ITEMOFLIST": "елемент %1 з %2",
  "DATA_ITEMNUMOFLIST": "елемент # %1 з %2",
  "DATA_LENGTHOFLIST": "довжина %1",
  "DATA_LISTCONTAINSITEM": "%1 містить %2?",
  "DATA_SHOWLIST": "показати список %1",
  "DATA_HIDELIST": "сховати список %1",
  "DATA_INDEX_ALL": "все",
  "DATA_INDEX_LAST": "останні",
  "DATA_INDEX_RANDOM": "випадково",
  "EVENT_WHENFLAGCLICKED": "коли %1 натиснуто",
  "EVENT_WHENTHISSPRITECLICKED": "коли спрайт натиснуто",
  "EVENT_WHENSTAGECLICKED": "коли сцену натиснуто",
  "EVENT_WHENTOUCHINGOBJECT": "коли цей спрайт торкнеться %1",
  "EVENT_WHENBROADCASTRECEIVED": "коли я отримую %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "коли тло зміниться на %1",
  "EVENT_WHENGREATERTHAN": "коли %1 > %2",
  "EVENT_WHENGREATERTHAN_TIMER": "таймер",
  "EVENT_WHENGREATERTHAN_LOUDNESS": "гучність",
  "EVENT_BROADCAST": "оповістити %1",
  "EVENT_BROADCASTANDWAIT": "оповістити %1 і чекати",
  "EVENT_WHENKEYPRESSED": "коли клавішу %1 натиснуто ",
  "EVENT_WHENKEYPRESSED_SPACE": "пропуск",
  "EVENT_WHENKEYPRESSED_LEFT": "стрілка ліворуч",
  "EVENT_WHENKEYPRESSED_RIGHT": "стрілка праворуч",
  "EVENT_WHENKEYPRESSED_DOWN": "стрілка вниз",
  "EVENT_WHENKEYPRESSED_UP": "стрілка вгору",
  "EVENT_WHENKEYPRESSED_ANY": "будь-яка",
  "LOOKS_SAYFORSECS": "говорити %1 %2 сек",
  "LOOKS_SAY": "говорити %1",
  "LOOKS_HELLO": "Привіт!",
  "LOOKS_THINKFORSECS": "подумати %1 %2 сек",
  "LOOKS_THINK": "подумати %1",
  "LOOKS_HMM": "Хмм...",
  "LOOKS_SHOW": "показати",
  "LOOKS_HIDE": "сховати",
  "LOOKS_HIDEALLSPRITES": "сховати усі спрайти",
  "LOOKS_EFFECT_COLOR": "колір",
  "LOOKS_EFFECT_FISHEYE": "роздуття",
  "LOOKS_EFFECT_WHIRL": "закручування",
  "LOOKS_EFFECT_PIXELATE": "пікселями",
  "LOOKS_EFFECT_MOSAIC": "мозаїка",
  "LOOKS_EFFECT_BRIGHTNESS": "яскравість",
  "LOOKS_EFFECT_GHOST": "привид",
  "LOOKS_CHANGEEFFECTBY": "змінити ефект %1 на %2",
  "LOOKS_SETEFFECTTO": "встановити ефект %1 в %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "очистити графічні ефекти",
  "LOOKS_CHANGESIZEBY": "змінити розмір на %1",
  "LOOKS_SETSIZETO": "задати розмір %1",
  "LOOKS_SIZE": "розмір",
  "LOOKS_CHANGESTRETCHBY": "змінити розтяг на %1",
  "LOOKS_SETSTRETCHTO": "задати розтяг %1 %",
  "LOOKS_SWITCHCOSTUMETO": "змінити образ на %1",
  "LOOKS_NEXTCOSTUME": "наступний образ",
  "LOOKS_SWITCHBACKDROPTO": "змінити тло на %1",
  "LOOKS_GOTOFRONTBACK": "помістити на %1 план",
  "LOOKS_GOTOFRONTBACK_FRONT": "передній",
  "LOOKS_GOTOFRONTBACK_BACK": "задній",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "перемістити %1 на %2 шар",
  "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "вперед",
  "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "назад",
  "LOOKS_BACKDROPNUMBERNAME": "тло %1",
  "LOOKS_COSTUMENUMBERNAME": "образ %1",
  "LOOKS_NUMBERNAME_NUMBER": "номер",
  "LOOKS_NUMBERNAME_NAME": "назва",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "змінити тло на %1 та чекати",
  "LOOKS_NEXTBACKDROP_BLOCK": "наступне тло",
  "LOOKS_NEXTBACKDROP": "наступне тло",
  "LOOKS_PREVIOUSBACKDROP": "попереднє тло",
  "LOOKS_RANDOMBACKDROP": "випадкове тло",
  "MOTION_MOVESTEPS": "перемістити на %1 кроків",
  "MOTION_TURNLEFT": "поворот %1 на %2 градусів",
  "MOTION_TURNRIGHT": "поворот %1 на %2 градусів",
  "MOTION_POINTINDIRECTION": "повернути в напрямку %1",
  "MOTION_POINTTOWARDS": "слідувати за %1",
  "MOTION_POINTTOWARDS_POINTER": "вказівник",
  "MOTION_POINTTOWARDS_RANDOM": "випадковий напрям",
  "MOTION_GOTO": "перейти до %1",
  "MOTION_GOTO_POINTER": "вказівник",
  "MOTION_GOTO_RANDOM": "випадкова позиція",
  "MOTION_GOTOXY": "перемістити в x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "ковзати %1 сек до x: %2 y: %3",
  "MOTION_GLIDETO": "ковзати %1 сек до %2",
  "MOTION_GLIDETO_POINTER": "вказівник",
  "MOTION_GLIDETO_RANDOM": "випадкова позиція",
  "MOTION_CHANGEXBY": "змінити x на %1",
  "MOTION_SETX": "задати x %1",
  "MOTION_CHANGEYBY": "змінити y на %1",
  "MOTION_SETY": "задати y %1",
  "MOTION_IFONEDGEBOUNCE": "якщо на межі, відбити",
  "MOTION_SETROTATIONSTYLE": "стиль обертання %1",
  "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "зліва-направо",
  "MOTION_SETROTATIONSTYLE_DONTROTATE": "не обертати",
  "MOTION_SETROTATIONSTYLE_ALLAROUND": "навколо",
  "MOTION_XPOSITION": "значення x",
  "MOTION_YPOSITION": "значення y",
  "MOTION_DIRECTION": "напрям",
  "MOTION_SCROLLRIGHT": "прокрутити праворуч %1",
  "MOTION_SCROLLUP": "прокрутити вгору %1",
  "MOTION_ALIGNSCENE": "вирівняти сцену %1",
  "MOTION_ALIGNSCENE_BOTTOMLEFT": "внизу-ліворуч",
  "MOTION_ALIGNSCENE_BOTTOMRIGHT": "вниз-праворуч",
  "MOTION_ALIGNSCENE_MIDDLE": "посередині",
  "MOTION_ALIGNSCENE_TOPLEFT": "зверху-ліворуч",
  "MOTION_ALIGNSCENE_TOPRIGHT": "зверху-праворуч",
  "MOTION_XSCROLL": "x прокрутка",
  "MOTION_YSCROLL": "y прокрутка",
  "MOTION_STAGE_SELECTED": "Обрано Сцену: немає блоків руху",
  "MOTION_MOVEGRIDS": "перемістити %1 сіток (40 кроків)",
  "OPERATORS_ADD": "%1 + %2",
  "OPERATORS_SUBTRACT": "%1 - %2",
  "OPERATORS_MULTIPLY": "%1 * %2",
  "OPERATORS_DIVIDE": "%1 / %2",
  "OPERATORS_RANDOM": "випадкове від %1 до %2",
  "OPERATORS_GT": "%1 > %2",
  "OPERATORS_LT": "%1 < %2",
  "OPERATORS_EQUALS": "%1 = %2",
  "OPERATORS_AND": "%1 і %2",
  "OPERATORS_OR": "%1 або %2",
  "OPERATORS_NOT": "не %1",
  "OPERATORS_JOIN": "з'єднати %1 %2",
  "OPERATORS_JOIN_APPLE": "яблуко",
  "OPERATORS_JOIN_BANANA": "банан",
  "OPERATORS_LETTEROF": "символ %1 у %2",
  "OPERATORS_LETTEROF_APPLE": "я",
  "OPERATORS_LENGTH": "довжина %1",
  "OPERATORS_CONTAINS": "%1 містить %2?",
  "OPERATORS_MOD": "остача %1 на %2",
  "OPERATORS_ROUND": "округлити %1",
  "OPERATORS_MATHOP": "%1 з %2",
  "OPERATORS_MATHOP_ABS": "abs",
  "OPERATORS_MATHOP_FLOOR": "менше ціле",
  "OPERATORS_MATHOP_CEILING": "більше ціле",
  "OPERATORS_MATHOP_SQRT": "sqrt",
  "OPERATORS_MATHOP_SIN": "sin",
  "OPERATORS_MATHOP_COS": "cos",
  "OPERATORS_MATHOP_TAN": "tan",
  "OPERATORS_MATHOP_ASIN": "asin",
  "OPERATORS_MATHOP_ACOS": "acos",
  "OPERATORS_MATHOP_ATAN": "atan",
  "OPERATORS_MATHOP_LN": "ln",
  "OPERATORS_MATHOP_LOG": "log",
  "OPERATORS_MATHOP_EEXP": "e ^",
  "OPERATORS_MATHOP_10EXP": "10 ^",
  "PROCEDURES_DEFINITION": "визначити %1",
  "SENSING_TOUCHINGOBJECT": "торкається %1?",
  "SENSING_TOUCHINGOBJECT_POINTER": "вказівник",
  "SENSING_TOUCHINGOBJECT_EDGE": "межа",
  "SENSING_TOUCHINGCOLOR": "торкається кольору %1?",
  "SENSING_COLORISTOUCHINGCOLOR": "колір %1 торкається %2?",
  "SENSING_DISTANCETO": "відстань до %1",
  "SENSING_DISTANCETO_POINTER": "вказівник",
  "SENSING_ASKANDWAIT": "запитати %1 і чекати",
  "SENSING_ASK_TEXT": "Як вас звати?",
  "SENSING_ANSWER": "відповідь",
  "SENSING_KEYPRESSED": "клавішу %1 натиснуто?",
  "SENSING_MOUSEDOWN": "мишку натиснуто?",
  "SENSING_MOUSEX": "мишка x",
  "SENSING_MOUSEY": "мишка y",
  "SENSING_SETDRAGMODE": "перетягувати %1",
  "SENSING_SETDRAGMODE_DRAGGABLE": "дозволено",
  "SENSING_SETDRAGMODE_NOTDRAGGABLE": "не дозволено",
  "SENSING_LOUDNESS": "гучність",
  "SENSING_LOUD": "гучно?",
  "SENSING_TIMER": "таймер",
  "SENSING_RESETTIMER": "перезапустити таймер",
  "SENSING_OF": "%1 з %2",
  "SENSING_OF_XPOSITION": "значення x",
  "SENSING_OF_YPOSITION": "значення y",
  "SENSING_OF_DIRECTION": "напрям",
  "SENSING_OF_COSTUMENUMBER": "образ #",
  "SENSING_OF_COSTUMENAME": "ім’я образу",
  "SENSING_OF_SIZE": "розмір",
  "SENSING_OF_VOLUME": "гучність",
  "SENSING_OF_BACKDROPNUMBER": "тло #",
  "SENSING_OF_BACKDROPNAME": "ім’я тла",
  "SENSING_OF_STAGE": "Сцена",
  "SENSING_CURRENT": "сьогодні %1",
  "SENSING_CURRENT_YEAR": "рік",
  "SENSING_CURRENT_MONTH": "місяць",
  "SENSING_CURRENT_DATE": "дата",
  "SENSING_CURRENT_DAYOFWEEK": "день тижня",
  "SENSING_CURRENT_HOUR": "година",
  "SENSING_CURRENT_MINUTE": "хвилина ",
  "SENSING_CURRENT_SECOND": "секунда",
  "SENSING_DAYSSINCE2000": "днів після 2000",
  "SENSING_USERNAME": "користувач",
  "SENSING_USERID": "користувач ID",
  "SOUND_PLAY": "відтворити звук %1",
  "SOUND_PLAYUNTILDONE": "відтворити звук %1 до кінця",
  "SOUND_STOPALLSOUNDS": "зупинити всі звуки",
  "SOUND_SETEFFECTO": "встановити ефект %1 в %2",
  "SOUND_CHANGEEFFECTBY": "змінити ефект %1 на %2",
  "SOUND_CLEAREFFECTS": "очистити звукові ефекти",
  "SOUND_EFFECTS_PITCH": "висота",
  "SOUND_EFFECTS_PAN": "панорама",
  "SOUND_CHANGEVOLUMEBY": "змінити гучність на %1",
  "SOUND_SETVOLUMETO": "встановити гучність %1%",
  "SOUND_VOLUME": "гучність",
  "SOUND_RECORD": "запис...",
  "CATEGORY_MOTION": "Рух",
  "CATEGORY_LOOKS": "Вигляд",
  "CATEGORY_SOUND": "Звук",
  "CATEGORY_EVENTS": "Події",
  "CATEGORY_CONTROL": "Керування",
  "CATEGORY_SENSING": "Датчики",
  "CATEGORY_OPERATORS": "Оператори",
  "CATEGORY_VARIABLES": "Змінні",
  "CATEGORY_MYBLOCKS": "Мої блоки",
  "DUPLICATE": "Дублювати",
  "DELETE": "Вилучити",
  "ADD_COMMENT": "Додати коментар",
  "REMOVE_COMMENT": "Вилучити коментар",
  "DELETE_BLOCK": "Вилучити блок",
  "DELETE_X_BLOCKS": "Вилучити %1 блоки",
  "DELETE_ALL_BLOCKS": "Вилучити всі %1 блоки?",
  "CLEAN_UP": "Впорядкувати блоки",
  "HELP": "Допомога",
  "UNDO": "Скасувати",
  "REDO": "Повернути",
  "FRAME": "Кадр",
  "COLLAPSED_X_BLOCKS": "Згорнуто %1 блоків",
  "COLOR": "Колір",
  "CREATE_FRAME": "Створити Кадр",
  "EDIT_PROCEDURE": "Правка",
  "SHOW_PROCEDURE_DEFINITION": "Перейти до визначення",
  "WORKSPACE_COMMENT_DEFAULT_TEXT": "Скажіть щось...",
  "COLOUR_HUE_LABEL": "Колір",
  "COLOUR_SATURATION_LABEL": "Насиченість",
  "COLOUR_BRIGHTNESS_LABEL": "Яскравість",
  "CHANGE_VALUE_TITLE": "Змінити значення:",
  "RENAME_VARIABLE": "Перейменувати змінну",
  "RENAME_VARIABLE_TITLE": "Перейменувати усі \"%1\" змінні на:",
  "RENAME_VARIABLE_MODAL_TITLE": "Перейменувати змінну",
  "NEW_VARIABLE": "Створити змінну",
  "NEW_VARIABLE_TITLE": "Нове ім'я змінної:",
  "VARIABLE_MODAL_TITLE": "Нова змінна",
  "VARIABLE_ALREADY_EXISTS": "Змінна з іменем \"%1\" вже існує.",
  "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "Ім'я змінної \"%1\" вже використано для змінної з типом \"%2\".",
  "DELETE_VARIABLE_CONFIRMATION": "Вилучити %1 використання змінної \"%2\"?",
  "CANNOT_DELETE_VARIABLE_PROCEDURE": "Не можна вилучити змінну \"%1\" оскільки вона визначена у функції \"%2\"",
  "DELETE_VARIABLE": "Вилучити змінну '%1'",
  "DISABLED_VARIABLE": 'Цю "%1" можна видалити або перейменувати тільки на сцені.',
  "VARIABLE": "змінна",
  "LIST": "список",
  "NEW_PROCEDURE": "Створити блок",
  "PROCEDURE_ALREADY_EXISTS": "Процедура з іменем '%1' вже існує",
  "PROCEDURE_DEFAULT_NAME": "назва блоку",
  "PROCEDURE_USED": "Щоб видалити цей блок, спочатку видаліть усі його використання",
  "Global_PROCEDURE_USED": "Щоб видалити визначення блоку, спершу видаліть усі використання блоку зі спрайта [%1]",
  "NEW_LIST": "Створити список",
  "NEW_LIST_TITLE": "Нове ім’я списку:",
  "LIST_MODAL_TITLE": "Новий список",
  "LIST_ALREADY_EXISTS": "Список з іменем '%1' вже існує",
  "RENAME_LIST_TITLE": "Перейменувати усі списки \"%1\" на:",
  "RENAME_LIST_MODAL_TITLE": "Перейменувати список",
  "DEFAULT_LIST_ITEM": "щось",
  "DELETE_LIST": "Вилучити список \"%1\"",
  "RENAME_LIST": "Перейменувати список",
  "NEW_BROADCAST_MESSAGE": "Нове повідомлення",
  "NEW_BROADCAST_MESSAGE_TITLE": "Нове ім’я повідомлення:",
  "BROADCAST_MODAL_TITLE": "Нове повідомлення",
  "DEFAULT_BROADCAST_MESSAGE_NAME": "повідомлення1",
  "PROCEDURE_RETURN": "повернути %1",
};

Blockly.ScratchMsgs.locales["zh-cn"] =
{
  "CONTROL_FOREVER": "重复执行",
  "CONTROL_REPEAT": "重复执行 %1 次",
  "CONTROL_IF": "如果 %1 那么",
  "CONTROL_ELSE": "否则",
  "CONTROL_STOP": "停止",
  "CONTROL_STOP_ALL": "全部脚本",
  "CONTROL_STOP_THIS": "这个脚本",
  "CONTROL_STOP_OTHER": "该角色的其他脚本",
  "CONTROL_WAIT": "等待 %1 秒",
  "CONTROL_WAITUNTIL": "等待 %1",
  "CONTROL_REPEATUNTIL": "重复执行直到 %1",
  "CONTROL_WHILE": "当 %1 重复执行",
  "CONTROL_FOREACH": "对于 %2 中的每个 %1",
  "CONTROL_STARTASCLONE": "当作为克隆体启动时",
  "CONTROL_CREATECLONEOF": "克隆 %1",
  "CONTROL_CREATECLONEOF_MYSELF": "自己",
  "CONTROL_DELETETHISCLONE": "删除此克隆体",
  "CONTROL_COUNTER": "计数器",
  "CONTROL_INCRCOUNTER": "计数器加一",
  "CONTROL_CLEARCOUNTER": "计数器归零",
  "CONTROL_ALLATONCE": "所有脚本",
  "DATA_SETVARIABLETO": "将 %1 设为 %2",
  "DATA_CHANGEVARIABLEBY": "将 %1 增加 %2",
  "DATA_SHOWVARIABLE": "显示变量 %1",
  "DATA_HIDEVARIABLE": "隐藏变量 %1",
  "DATA_ADDTOLIST": "将 %1 加入 %2",
  "DATA_DELETEOFLIST": "删除 %2 的第 %1 项",
  "DATA_DELETEALLOFLIST": "删除 %1 的全部项目",
  "DATA_INSERTATLIST": "在 %3 的第 %2 项前插入 %1",
  "DATA_REPLACEITEMOFLIST": "将 %2 的第 %1 项替换为 %3",
  "DATA_ITEMOFLIST": "%2 的第 %1 项",
  "DATA_ITEMNUMOFLIST": "%2 中第一个 %1 的编号",
  "DATA_LENGTHOFLIST": "%1 的项目数",
  "DATA_LISTCONTAINSITEM": "%1 包含 %2 ?",
  "DATA_SHOWLIST": "显示列表 %1",
  "DATA_HIDELIST": "隐藏列表 %1",
  "DATA_INDEX_ALL": "全部",
  "DATA_INDEX_LAST": "末尾",
  "DATA_INDEX_RANDOM": "随机",
  "EVENT_WHENFLAGCLICKED": "当 %1 被点击",
  "EVENT_WHENTHISSPRITECLICKED": "当角色被点击",
  "EVENT_WHENSTAGECLICKED": "当舞台被点击",
  "EVENT_WHENTOUCHINGOBJECT": "当该角色碰到 %1",
  "EVENT_WHENBROADCASTRECEIVED": "当接收到 %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "当背景切换到 %1",
  "EVENT_WHENGREATERTHAN": "当 %1 > %2",
  "EVENT_WHENGREATERTHAN_TIMER": "计时器",
  "EVENT_WHENGREATERTHAN_LOUDNESS": "响度",
  "EVENT_BROADCAST": "广播 %1",
  "EVENT_BROADCASTANDWAIT": "广播 %1 并等待",
  "EVENT_WHENKEYPRESSED": "当按下 %1 键",
  "EVENT_WHENKEYPRESSED_SPACE": "空格",
  "EVENT_WHENKEYPRESSED_LEFT": "←",
  "EVENT_WHENKEYPRESSED_RIGHT": "→",
  "EVENT_WHENKEYPRESSED_DOWN": "↓",
  "EVENT_WHENKEYPRESSED_UP": "↑",
  "EVENT_WHENKEYPRESSED_ANY": "任意",
  "LOOKS_SAYFORSECS": "说 %1 %2 秒",
  "LOOKS_SAY": "说 %1",
  "LOOKS_HELLO": "你好！",
  "LOOKS_THINKFORSECS": "思考 %1 %2 秒",
  "LOOKS_THINK": "思考 %1",
  "LOOKS_HMM": "嗯……",
  "LOOKS_SHOW": "显示",
  "LOOKS_HIDE": "隐藏",
  "LOOKS_HIDEALLSPRITES": "隐藏所有角色",
  "LOOKS_EFFECT_COLOR": "颜色",
  "LOOKS_EFFECT_FISHEYE": "鱼眼",
  "LOOKS_EFFECT_WHIRL": "漩涡",
  "LOOKS_EFFECT_PIXELATE": "像素化",
  "LOOKS_EFFECT_MOSAIC": "马赛克",
  "LOOKS_EFFECT_BRIGHTNESS": "亮度",
  "LOOKS_EFFECT_GHOST": "虚像",
  "LOOKS_CHANGEEFFECTBY": "将 %1 特效增加 %2",
  "LOOKS_SETEFFECTTO": "将 %1 特效设定为 %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "清除图形特效",
  "LOOKS_CHANGESIZEBY": "将大小增加 %1",
  "LOOKS_SETSIZETO": "将大小设为 %1",
  "LOOKS_SIZE": "大小",
  "LOOKS_CHANGESTRETCHBY": "伸缩%1",
  "LOOKS_SETSTRETCHTO": "设置伸缩为%1 %",
  "LOOKS_SWITCHCOSTUMETO": "将造型切换为 %1",
  "LOOKS_NEXTCOSTUME": "下一个造型",
  "LOOKS_SWITCHBACKDROPTO": "将背景切换为 %1",
  "LOOKS_GOTOFRONTBACK": "移到最 %1 ",
  "LOOKS_GOTOFRONTBACK_FRONT": "前面",
  "LOOKS_GOTOFRONTBACK_BACK": "后面",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "%1 %2 层",
  "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "前移",
  "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "后移",
  "LOOKS_BACKDROPNUMBERNAME": "背景 %1",
  "LOOKS_COSTUMENUMBERNAME": "造型 %1",
  "LOOKS_NUMBERNAME_NUMBER": "编号",
  "LOOKS_NUMBERNAME_NAME": "名称",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "换成 %1 背景并等待",
  "LOOKS_NEXTBACKDROP_BLOCK": "下一个背景",
  "LOOKS_NEXTBACKDROP": "下一个背景",
  "LOOKS_PREVIOUSBACKDROP": "上一个背景",
  "LOOKS_RANDOMBACKDROP": "随机背景",
  "MOTION_MOVESTEPS": "移动 %1 步",
  "MOTION_TURNLEFT": "向左旋转 %1 %2 度",
  "MOTION_TURNRIGHT": "向右旋转 %1 %2 度",
  "MOTION_POINTINDIRECTION": "面向 %1 方向",
  "MOTION_POINTTOWARDS": "面向 %1",
  "MOTION_POINTTOWARDS_POINTER": "鼠标指针",
  "MOTION_POINTTOWARDS_RANDOM": "随机方向",
  "MOTION_GOTO": "移到 %1",
  "MOTION_GOTO_POINTER": "鼠标指针",
  "MOTION_GOTO_RANDOM": "随机位置",
  "MOTION_GOTOXY": "移到 x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "在 %1 秒内滑行到 x: %2 y: %3",
  "MOTION_GLIDETO": "在 %1 秒内滑行到 %2",
  "MOTION_GLIDETO_POINTER": "鼠标指针",
  "MOTION_GLIDETO_RANDOM": "随机位置",
  "MOTION_CHANGEXBY": "将x坐标增加 %1",
  "MOTION_SETX": "将x坐标设为 %1",
  "MOTION_CHANGEYBY": "将y坐标增加 %1",
  "MOTION_SETY": "将y坐标设为 %1",
  "MOTION_IFONEDGEBOUNCE": "碰到边缘就反弹",
  "MOTION_SETROTATIONSTYLE": "将旋转方式设为 %1",
  "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "左右翻转",
  "MOTION_SETROTATIONSTYLE_DONTROTATE": "不可旋转",
  "MOTION_SETROTATIONSTYLE_ALLAROUND": "任意旋转",
  "MOTION_XPOSITION": "x 坐标",
  "MOTION_YPOSITION": "y 坐标",
  "MOTION_DIRECTION": "方向",
  "MOTION_SCROLLRIGHT": "向右滚动 %1",
  "MOTION_SCROLLUP": "向上滚动 %1",
  "MOTION_ALIGNSCENE": "和场景 %1 对齐",
  "MOTION_ALIGNSCENE_BOTTOMLEFT": "左下角",
  "MOTION_ALIGNSCENE_BOTTOMRIGHT": "右下角",
  "MOTION_ALIGNSCENE_MIDDLE": "中间",
  "MOTION_ALIGNSCENE_TOPLEFT": "左上角",
  "MOTION_ALIGNSCENE_TOPRIGHT": "右上角",
  "MOTION_XSCROLL": "x滚动位置",
  "MOTION_YSCROLL": "y滚动位置",
  "MOTION_STAGE_SELECTED": "选中了舞台：不可使用运动类积木",
  "MOTION_MOVEGRIDS": "移动 %1 格(40步)",
  "OPERATORS_ADD": "%1 + %2",
  "OPERATORS_SUBTRACT": "%1 - %2",
  "OPERATORS_MULTIPLY": "%1 * %2",
  "OPERATORS_DIVIDE": "%1 / %2",
  "OPERATORS_RANDOM": "在 %1 和 %2 之间取随机数",
  "OPERATORS_GT": "%1 > %2",
  "OPERATORS_LT": "%1 < %2",
  "OPERATORS_EQUALS": "%1 = %2",
  "OPERATORS_AND": "%1 与 %2",
  "OPERATORS_OR": "%1 或 %2",
  "OPERATORS_NOT": "%1 不成立",
  "OPERATORS_JOIN": "连接 %1 和 %2",
  "OPERATORS_JOIN_APPLE": "苹果",
  "OPERATORS_JOIN_BANANA": "香蕉",
  "OPERATORS_LETTEROF": "%2 的第 %1 个字符",
  "OPERATORS_LETTEROF_APPLE": "果",
  "OPERATORS_LENGTH": "%1 的字符数",
  "OPERATORS_CONTAINS": "%1 包含 %2 ?",
  "OPERATORS_MOD": "%1 除以 %2 的余数",
  "OPERATORS_ROUND": "四舍五入 %1",
  "OPERATORS_MATHOP": "%1 %2",
  "OPERATORS_MATHOP_ABS": "绝对值",
  "OPERATORS_MATHOP_FLOOR": "向下取整",
  "OPERATORS_MATHOP_CEILING": "向上取整",
  "OPERATORS_MATHOP_SQRT": "平方根",
  "OPERATORS_MATHOP_SIN": "sin",
  "OPERATORS_MATHOP_COS": "cos",
  "OPERATORS_MATHOP_TAN": "tan",
  "OPERATORS_MATHOP_ASIN": "asin",
  "OPERATORS_MATHOP_ACOS": "acos",
  "OPERATORS_MATHOP_ATAN": "atan",
  "OPERATORS_MATHOP_LN": "ln",
  "OPERATORS_MATHOP_LOG": "log",
  "OPERATORS_MATHOP_EEXP": "e ^",
  "OPERATORS_MATHOP_10EXP": "10 ^",
  "PROCEDURES_DEFINITION": "定义 %1",
  "SENSING_TOUCHINGOBJECT": "碰到 %1 ?",
  "SENSING_TOUCHINGOBJECT_POINTER": "鼠标指针",
  "SENSING_TOUCHINGOBJECT_EDGE": "舞台边缘",
  "SENSING_TOUCHINGCOLOR": "碰到颜色 %1 ?",
  "SENSING_COLORISTOUCHINGCOLOR": "颜色 %1 碰到 %2 ?",
  "SENSING_DISTANCETO": "到 %1 的距离",
  "SENSING_DISTANCETO_POINTER": "鼠标指针",
  "SENSING_ASKANDWAIT": "询问 %1 并等待",
  "SENSING_ASK_TEXT": "你叫什么名字？",
  "SENSING_ANSWER": "回答",
  "SENSING_KEYPRESSED": "按键 %1 是否按下?",
  "SENSING_MOUSEDOWN": "按下鼠标?",
  "SENSING_MOUSEX": "鼠标的x坐标",
  "SENSING_MOUSEY": "鼠标的y坐标",
  "SENSING_SETDRAGMODE": "将拖动模式设为 %1",
  "SENSING_SETDRAGMODE_DRAGGABLE": "可拖动",
  "SENSING_SETDRAGMODE_NOTDRAGGABLE": "不可拖动",
  "SENSING_LOUDNESS": "响度",
  "SENSING_LOUD": "响声？",
  "SENSING_TIMER": "计时器",
  "SENSING_RESETTIMER": "计时器归零",
  "SENSING_OF": "%2 的 %1",
  "SENSING_OF_XPOSITION": "x 坐标",
  "SENSING_OF_YPOSITION": "y 坐标",
  "SENSING_OF_DIRECTION": "方向",
  "SENSING_OF_COSTUMENUMBER": "造型编号",
  "SENSING_OF_COSTUMENAME": "造型名称",
  "SENSING_OF_SIZE": "大小",
  "SENSING_OF_VOLUME": "音量",
  "SENSING_OF_BACKDROPNUMBER": "背景编号",
  "SENSING_OF_BACKDROPNAME": "背景名称",
  "SENSING_OF_STAGE": "舞台",
  "SENSING_CURRENT": "当前时间的 %1",
  "SENSING_CURRENT_YEAR": "年",
  "SENSING_CURRENT_MONTH": "月",
  "SENSING_CURRENT_DATE": "日",
  "SENSING_CURRENT_DAYOFWEEK": "星期",
  "SENSING_CURRENT_HOUR": "时",
  "SENSING_CURRENT_MINUTE": "分",
  "SENSING_CURRENT_SECOND": "秒",
  "SENSING_DAYSSINCE2000": "2000年至今的天数",
  "SENSING_USERNAME": "用户名",
  "SENSING_USERID": "用户id",
  "SOUND_PLAY": "播放声音 %1",
  "SOUND_PLAYUNTILDONE": "播放 %1 声音，直到播放完毕",
  "SOUND_STOPALLSOUNDS": "停止所有声音",
  "SOUND_SETEFFECTO": "将 %1 音效设为 %2",
  "SOUND_CHANGEEFFECTBY": "将 %1 音效增加 %2",
  "SOUND_CLEAREFFECTS": "清除音效",
  "SOUND_EFFECTS_PITCH": "音调",
  "SOUND_EFFECTS_PAN": "左右平衡",
  "SOUND_CHANGEVOLUMEBY": "将音量增加 %1",
  "SOUND_SETVOLUMETO": "将音量设为 %1%",
  "SOUND_VOLUME": "音量",
  "SOUND_RECORD": "录制…",
  "CATEGORY_MOTION": "动作",
  "CATEGORY_LOOKS": "外观",
  "CATEGORY_SOUND": "声音",
  "CATEGORY_EVENTS": "事件",
  "CATEGORY_CONTROL": "控制",
  "CATEGORY_SENSING": "侦测",
  "CATEGORY_OPERATORS": "运算",
  "CATEGORY_VARIABLES": "变量",
  "CATEGORY_MYBLOCKS": "自制积木",
  "DUPLICATE": "复制",
  "DELETE": "删除",
  "ADD_COMMENT": "添加注释",
  "REMOVE_COMMENT": "删除注释",
  "DELETE_BLOCK": "删除",
  "DELETE_X_BLOCKS": "删除 %1 个积木",
  "DELETE_ALL_BLOCKS": "删除全部 %1 个积木？",
  "CLEAN_UP": "整理积木",
  "COLLAPSED_X_BLOCKS": "已折叠 %1 块积木",
  "HELP": "帮助",
  "UNDO": "撤销",
  "REDO": "重做",
  "FRAME": "代码框",
  "CREATE_FRAME": "创建代码框",
  "COLOR": "颜色",
  "EDIT_PROCEDURE": "编辑",
  "SHOW_PROCEDURE_DEFINITION": "查看定义",
  "WORKSPACE_COMMENT_DEFAULT_TEXT": "说些什么……",
  "COLOUR_HUE_LABEL": "颜色",
  "COLOUR_SATURATION_LABEL": "饱和度",
  "COLOUR_BRIGHTNESS_LABEL": "亮度",
  "CHANGE_VALUE_TITLE": "更改变量：",
  "RENAME_VARIABLE": "修改变量名",
  "RENAME_VARIABLE_TITLE": "将所有的「%1」变量名改为：",
  "RENAME_VARIABLE_MODAL_TITLE": "修改变量名",
  "NEW_VARIABLE": "建立一个变量",
  "NEW_VARIABLE_TITLE": "新变量名：",
  "VARIABLE_MODAL_TITLE": "新建变量",
  "VARIABLE_ALREADY_EXISTS": "已经存在名为「%1」的变量。",
  "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "已经存在一个名为「%1」的变量，其类型为「%2」。",
  "DELETE_VARIABLE_CONFIRMATION": "删除%1处「%2」变量吗？",
  "CANNOT_DELETE_VARIABLE_PROCEDURE": "无法删除变量「%1」，因为函数「%2」的定义中用到了它",
  "DELETE_VARIABLE": "删除变量「%1」",
  "DISABLED_VARIABLE": "该%1只能在舞台背景中进行修改或删除",
  "VARIABLE": "变量",
  "LIST": "列表",
  "NEW_PROCEDURE": "制作新的积木",
  "PROCEDURE_ALREADY_EXISTS": "已经存在名为「%1」的自定义积木。",
  "PROCEDURE_DEFAULT_NAME": "积木名称",
  "PROCEDURE_USED": "在删除一个积木定义前，请先把该积木从所有使用的地方删除。",
  "Global_PROCEDURE_USED": "在删除一个全局积木定义前，请先把该积木从正在使用它的[ %1 ]中删除。",
  "NEW_LIST": "建立一个列表",
  "NEW_LIST_TITLE": "新的列表名：",
  "LIST_MODAL_TITLE": "新建列表",
  "LIST_ALREADY_EXISTS": "名为 「%1」 的列表已存在。",
  "RENAME_LIST_TITLE": "将所有的「%1」列表改名为：",
  "RENAME_LIST_MODAL_TITLE": "修改列表名",
  "DEFAULT_LIST_ITEM": "东西",
  "DELETE_LIST": "删除「%1」列表",
  "RENAME_LIST": "修改列表名",
  "NEW_BROADCAST_MESSAGE": "新消息",
  "NEW_BROADCAST_MESSAGE_TITLE": "新消息的名称：",
  "BROADCAST_MODAL_TITLE": "新消息",
  "DEFAULT_BROADCAST_MESSAGE_NAME": "消息1",
  "PROCEDURE_RETURN": "返回 %1",
};
// End of combined translations
